# Generated by Django 5.2.1 on 2025-10-21 12:03

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_savings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('PROCESSING', 'En Proceso'), ('COMPLETED', 'Completado')], default='ACTIVE', max_length=20)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'trading_match_selection',
            },
        ),
        migrations.CreateModel(
            name='MatchSelectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buyer_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('seller_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'trading_match_selection_item',
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_volume', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobado por admin'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrato de Orden',
                'verbose_name_plural': 'Contratos de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('payment_method', models.CharField(default='CREDIT_CARD', max_length=50)),
                ('reference', models.CharField(default='test_001_devise', max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'Iniciado'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='INITIATED', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'trading_payment_record',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('units', models.PositiveIntegerField()),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('units_executed', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fully_executed_at', models.DateTimeField(blank=True, null=True)),
                ('partially_executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('MATCHED', 'Emparejada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('PARTIALLY_EXECUTED', 'Parcialmente Ejecutada'), ('FULLY_EXECUTED', 'Completamente Ejecutada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('processing_payment_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('units', models.PositiveIntegerField()),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('units_executed', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fully_executed_at', models.DateTimeField(blank=True, null=True)),
                ('partially_executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('PARTIALLY_EXECUTED', 'Parcialmente Ejecutada'), ('FULLY_EXECUTED', 'Completamente Ejecutada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=30)),
                ('reserved_tokens_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Órdenes de venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REVERTED', 'Revertido')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'trading_token_transfer_record',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
