# Generated by Django 5.2.1 on 2025-09-17 17:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_volume', models.IntegerField(default=0)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_books', to='fund.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('units', models.PositiveIntegerField()),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('units_executed', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fully_executed_at', models.DateTimeField(blank=True, null=True)),
                ('partially_executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('MATCHED', 'Emparejada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('PARTIALLY_EXECUTED', 'Parcialmente Ejecutada'), ('FULLY_EXECUTED', 'Completamente Ejecutada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('processing_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='fund.fund')),
                ('supplier_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_savings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('PROCESSING', 'En Proceso'), ('COMPLETED', 'Completado')], default='ACTIVE', max_length=20)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_selection', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.purchaseorder')),
            ],
            options={
                'db_table': 'trading_match_selection',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('units', models.PositiveIntegerField()),
                ('available_units', models.PositiveIntegerField(blank=True, null=True)),
                ('units_executed', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fully_executed_at', models.DateTimeField(blank=True, null=True)),
                ('partially_executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('PARTIALLY_EXECUTED', 'Parcialmente Ejecutada'), ('FULLY_EXECUTED', 'Completamente Ejecutada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=30)),
                ('reserved_tokens_info', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='fund.fund')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Órdenes de venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSelectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buyer_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('seller_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.matchselection')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.salesorder')),
            ],
            options={
                'db_table': 'trading_match_selection_item',
            },
        ),
        migrations.AddField(
            model_name='matchselection',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.salesorder'),
        ),
        migrations.CreateModel(
            name='TokenTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REVERTED', 'Revertido')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.salesorder')),
                ('selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.matchselection')),
                ('selection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfer_records', to='trading.matchselectionitem')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_token_transfer_record',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fund.fund')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.salesorder')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('payment_method', models.CharField(default='CREDIT_CARD', max_length=50)),
                ('reference', models.CharField(default='test_001_devise', max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'Iniciado'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='INITIATED', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='trading.purchaseorder')),
            ],
            options={
                'db_table': 'trading_payment_record',
                'indexes': [models.Index(fields=['reference'], name='trading_pay_referen_093235_idx'), models.Index(fields=['status', 'initiated_at'], name='trading_pay_status_dd101d_idx'), models.Index(fields=['purchase_order', 'status'], name='trading_pay_purchas_098bfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobado por admin'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='trading.salesorder')),
            ],
            options={
                'verbose_name': 'Contrato de Orden',
                'verbose_name_plural': 'Contratos de Órdenes',
                'unique_together': {('purchase_order', 'sales_order')},
            },
        ),
        migrations.AddIndex(
            model_name='matchselectionitem',
            index=models.Index(fields=['selection', 'sales_order', 'purchase_order'], name='trading_mat_selecti_5c52c6_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselectionitem',
            index=models.Index(fields=['units'], name='trading_mat_units_241e50_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['expires_at'], name='trading_mat_expires_77b466_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['purchase_order', 'sales_order', 'status'], name='trading_mat_purchas_65c81f_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['selected_at'], name='trading_mat_selecte_736bed_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['purchase_order', 'status'], name='trading_tok_purchas_2f7f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['sales_order', 'status'], name='trading_tok_sales_o_c233a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['token_id'], name='trading_tok_token_i_a71802_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['status', 'initiated_at'], name='trading_tok_status_85c276_idx'),
        ),
    ]
