# Generated by Django 5.2.1 on 2025-10-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0002_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchselection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_selection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchselectionitem',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.matchselection'),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_books', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='ordercontract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='trading.purchaseorder'),
        ),
        migrations.AddField(
            model_name='ordercontract',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='trading.purchaseorder'),
        ),
        migrations.AddField(
            model_name='matchselectionitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.purchaseorder'),
        ),
        migrations.AddField(
            model_name='matchselection',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.purchaseorder'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='seller_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercontract',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='trading.salesorder'),
        ),
        migrations.AddField(
            model_name='matchselectionitem',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.salesorder'),
        ),
        migrations.AddField(
            model_name='matchselection',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.salesorder'),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.purchaseorder'),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.salesorder'),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.matchselection'),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='selection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfer_records', to='trading.matchselectionitem'),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.purchaseorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trading.salesorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['reference'], name='trading_pay_referen_093235_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status', 'initiated_at'], name='trading_pay_status_dd101d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['purchase_order', 'status'], name='trading_pay_purchas_098bfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordercontract',
            unique_together={('purchase_order', 'sales_order')},
        ),
        migrations.AddIndex(
            model_name='matchselectionitem',
            index=models.Index(fields=['selection', 'sales_order', 'purchase_order'], name='trading_mat_selecti_5c52c6_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselectionitem',
            index=models.Index(fields=['units'], name='trading_mat_units_241e50_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['expires_at'], name='trading_mat_expires_77b466_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['purchase_order', 'sales_order', 'status'], name='trading_mat_purchas_65c81f_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['selected_at'], name='trading_mat_selecte_736bed_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['purchase_order', 'status'], name='trading_tok_purchas_2f7f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['sales_order', 'status'], name='trading_tok_sales_o_c233a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['token_id'], name='trading_tok_token_i_a71802_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['status', 'initiated_at'], name='trading_tok_status_85c276_idx'),
        ),
    ]
