# Generated by Django 5.2.1 on 2025-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20250410_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('EXPIRED', 'Expirada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('EXPIRED', 'Expirada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
