# Generated by Django 5.2.1 on 2026-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransferrecord',
            name='token_id',
            field=models.CharField(max_length=100),
        ),
    ]
