# Generated by Django 5.2.1 on 2025-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_purchaseorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('EXPIRED', 'Expirada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('EXPIRED', 'Expirada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
