# Generated by Django 5.2.1 on 2026-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_tokentransferrecord_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='origen',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='origen',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
