# Generated by Django 5.2.1 on 2026-02-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_purchaseorder_origen_salesorder_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='origen',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='origen',
            new_name='origin',
        ),
    ]
