# Generated by Django 5.2.1 on 2025-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_purchaseorder_status_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='available_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='available_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
