# Generated by Django 5.2.1 on 2025-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_purchaseorder_available_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='completed_at',
            new_name='fully_executed_at',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='processing_payment_at',
            new_name='partially_executed_at',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='completed_at',
            new_name='fully_executed_at',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='paid_at',
            new_name='partially_executed_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='processing_payment_at',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('MATCHED', 'Emparejada'), ('PROCESSING_PAYMENT', 'Procesando Pago'), ('PAID', 'Pagada'), ('PARTIALLY_EXECUTED', 'Parcialmente Ejecutada'), ('FULLY_EXECUTED', 'Completamente Ejecutada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('MATCHED', 'Emparejada'), ('MATCHES_SELECTED', 'Matches Seleccionados'), ('PARTIALLY_EXECUTED', 'Parcialmente Ejecutada'), ('FULLY_EXECUTED', 'Completamente Ejecutada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=30),
        ),
    ]
