# Generated by Django 5.2.1 on 2026-03-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_origen_purchaseorder_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='assistance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='assisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='authorization_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='authorization_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_staff_assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='assistance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='assisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='authorization_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='authorization_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_staff_assisted',
            field=models.BooleanField(default=False),
        ),
    ]
