# Generated by Django 5.2.1 on 2025-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_rename_completed_at_purchaseorder_fully_executed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='processing_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
