# Generated by Django 5.2.1 on 2025-07-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_purchaseorder_processing_payment_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
