# Generated by Django 5.2.1 on 2025-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_ordercontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='units_executed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='units_executed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
