# Generated by Django 5.2.4 on 2025-08-06 00:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_purchaseorder_units_executed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_savings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('PROCESSING', 'En Proceso'), ('COMPLETED', 'Completado')], default='ACTIVE', max_length=20)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_selections', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_selections', to='trading.purchaseorder')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_selections', to='trading.salesorder')),
            ],
            options={
                'db_table': 'trading_match_selection',
            },
        ),
        migrations.CreateModel(
            name='MatchSelectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buyer_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('seller_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.salesorder')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.matchselection')),
            ],
            options={
                'db_table': 'trading_match_selection_item',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('payment_method', models.CharField(default='CREDIT_CARD', max_length=50)),
                ('reference', models.CharField(default='test_001_devise', max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'Iniciado'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='INITIATED', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='trading.purchaseorder')),
            ],
            options={
                'db_table': 'trading_payment_record',
            },
        ),
        migrations.CreateModel(
            name='TokenTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REVERTED', 'Revertido')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('match_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.matchselectionitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.salesorder')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_token_transfer_record',
            },
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['expires_at'], name='trading_mat_expires_77b466_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['purchase_order', 'sales_order', 'status'], name='trading_mat_purchas_65c81f_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselection',
            index=models.Index(fields=['selected_at'], name='trading_mat_selecte_736bed_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselectionitem',
            index=models.Index(fields=['selection', 'sales_order', 'purchase_order'], name='trading_mat_selecti_5c52c6_idx'),
        ),
        migrations.AddIndex(
            model_name='matchselectionitem',
            index=models.Index(fields=['units'], name='trading_mat_units_241e50_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['reference'], name='trading_pay_referen_093235_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status', 'initiated_at'], name='trading_pay_status_dd101d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['purchase_order', 'status'], name='trading_pay_purchas_098bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['purchase_order', 'status'], name='trading_tok_purchas_2f7f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['sales_order', 'status'], name='trading_tok_sales_o_c233a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['token_id'], name='trading_tok_token_i_a71802_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransferrecord',
            index=models.Index(fields=['status', 'initiated_at'], name='trading_tok_status_85c276_idx'),
        ),
    ]
