# Generated by Django 5.2.4 on 2025-08-06 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_matchselection_matchselectionitem_paymentrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchselection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_selection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchselection',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='matchselection',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.salesorder'),
        ),
    ]
