# Generated by Django 5.2.4 on 2025-08-06 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_alter_matchselection_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='reserved_tokens_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchselection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_selection', to=settings.AUTH_USER_MODEL),
        ),
    ]
