# Generated by Django 5.2.4 on 2025-08-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_salesorder_reserved_tokens_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchselection',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='matchselection',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection', to='trading.salesorder'),
        ),
        migrations.AlterField(
            model_name='matchselectionitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='matchselectionitem',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_selection_items', to='trading.salesorder'),
        ),
    ]
