# Generated by Django 5.2.4 on 2025-08-14 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_alter_matchselection_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentransferrecord',
            name='match_item',
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.matchselection'),
        ),
        migrations.AddField(
            model_name='tokentransferrecord',
            name='selection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='trading.matchselectionitem'),
        ),
    ]
