# Generated by Django 5.2.4 on 2025-08-14 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_remove_tokentransferrecord_match_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransferrecord',
            name='selection_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transfer_records', to='trading.matchselectionitem'),
        ),
    ]
