# Generated by Django 5.2.1 on 2025-10-21 12:03

import apps.user.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('fund', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=126)),
                ('name', models.CharField(max_length=126)),
                ('description', models.CharField(max_length=126)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('indicative', models.CharField(max_length=32, verbose_name='indicativo')),
                ('phone', models.CharField(max_length=64, verbose_name='teléfono')),
                ('is_natural_person', models.BooleanField(default=True)),
                ('juridic_xlsx', models.FileField(blank=True, null=True, upload_to=apps.user.models.owner_file_path)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('document_front_image', models.ImageField(upload_to=apps.user.models.owner_file_path)),
                ('document_back_image', models.ImageField(blank=True, null=True, upload_to=apps.user.models.owner_file_path)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=apps.user.models.owner_file_path)),
                ('expedition_date', models.DateField(blank=True, null=True)),
                ('kyc_validated', models.CharField(choices=[('pending_document', 'Pendiente por cargar documento'), ('ready_for_kyc', 'Pendiente por subir a WeeTrust'), ('validating_document', 'Documento en Validación'), ('fail_document', 'Fallo en Documento'), ('sucessfull_document', 'KYC Validado')], default='pending_document', max_length=64)),
                ('mail_delivery', models.CharField(blank=True, choices=[('E-MAIL', 'Correo Electronico'), ('DOMICILIO', 'A la Dirección del Domicilio'), ('TRABAJO', 'A la Direccion del Trabajo')], max_length=126, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('referred_by_code', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('entity_nit', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('last_password_change', models.DateField(blank=True, null=True)),
                ('last_failed_access', models.DateTimeField(blank=True, null=True)),
                ('last_frontend_access', models.DateTimeField(auto_now_add=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('birth_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_city', to='cities_light.subregion')),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_country', to='cities_light.country')),
                ('birth_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_region', to='cities_light.region')),
                ('doc_city_expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.subregion')),
                ('doc_country_expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country')),
                ('doc_region_expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.region')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('local_id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.idtype')),
            ],
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('recovery_code', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=126)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.role'),
        ),
        migrations.CreateModel(
            name='UserAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('VIEW_PROFILE', 'Ver perfil completo'), ('EDIT_PROFILE', 'Editar información básica'), ('TRADING_VIEW', 'Ver órdenes de trading'), ('TRADING_MANAGE', 'Gestionar órdenes de trading'), ('FULL_ACCESS', 'Acceso total temporal'), ('CREATE_PURCHASE_ORDER', 'Crear órdenes de compra'), ('CREATE_SALES_ORDER', 'Crear órdenes de venta'), ('CANCEL_ORDERS', 'Cancelar mis órdenes'), ('VIEW_ORDERS', 'Ver mis órdenes'), ('SELECT_MATCHES', 'Seleccionar matches para mis órdenes'), ('AUTO_SELECT_MATCHES', 'Permitir selección automática'), ('CANCEL_SELECTIONS', 'Cancelar selecciones de matches'), ('EXECUTE_PAYMENTS', 'Ejecutar pagos de mis órdenes'), ('VIEW_PAYMENT_STATUS', 'Ver estado de pagos'), ('TRADING_FULL_ACCESS', 'Acceso completo a trading'), ('FUND_SPECIFIC_ACCESS', 'Acceso específico a un fondo')], help_text='Tipo de permiso otorgado', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('REVOKED', 'Revocado')], default='ACTIVE', max_length=10)),
                ('reason', models.TextField(help_text='Motivo por el cual se otorga el permiso')),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo por orden (null = sin límite)', max_digits=15, null=True)),
                ('max_daily_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo diario (null = sin límite)', max_digits=15, null=True)),
                ('max_units_per_order', models.PositiveIntegerField(blank=True, help_text='Unidades máximas por orden (null = sin límite)', null=True)),
                ('auto_approve_under_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-aprobar órdenes menores a este monto', max_digits=15, null=True)),
                ('require_confirmation', models.BooleanField(default=True, help_text='Requiere confirmación del usuario antes de ejecutar')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Máximo número de usos (null = ilimitado)', null=True)),
                ('last_amount_used', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración del permiso')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(help_text='Admin que recibe el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, help_text='Fondo específico al que aplica (null = todos los fondos)', null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
                ('user', models.ForeignKey(help_text='Usuario que otorga el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario a Admin',
                'verbose_name_plural': 'Permisos de Usuario a Admin',
                'unique_together': {('user', 'admin_user', 'permission_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('indicative', 'phone')},
        ),
        migrations.CreateModel(
            name='PermissionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('units', models.PositiveIntegerField(null=True)),
                ('success', models.BooleanField()),
                ('result_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.salesorder')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='user.useradminpermission')),
            ],
            options={
                'indexes': [models.Index(fields=['permission', 'executed_at'], name='user_permis_permiss_0fa1be_idx'), models.Index(fields=['action_type', 'success'], name='user_permis_action__5c119f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingPermissionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_description', models.TextField()),
                ('action_data', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(null=True)),
                ('user_response', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useradminpermission')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='user_pendin_status_4521a8_idx'), models.Index(fields=['permission', 'requested_at'], name='user_pendin_permiss_ee45a2_idx')],
            },
        ),
    ]
