# Generated by Django 3.2.18 on 2025-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_last_frontend_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity_nit',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
