# Generated by Django 5.2.4 on 2025-07-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_entity_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('VIEW_PROFILE', 'Ver perfil completo'), ('EDIT_PROFILE', 'Editar información básica'), ('TRADING_VIEW', 'Ver órdenes de trading'), ('TRADING_MANAGE', 'Gestionar órdenes de trading'), ('FULL_ACCESS', 'Acceso total temporal')], help_text='Tipo de permiso otorgado', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('REVOKED', 'Revocado')], default='ACTIVE', max_length=10)),
                ('reason', models.TextField(help_text='Motivo por el cual se otorga el permiso')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración del permiso')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(help_text='Admin que recibe el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario que otorga el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario a Admin',
                'verbose_name_plural': 'Permisos de Usuario a Admin',
                'unique_together': {('user', 'admin_user', 'permission_type')},
            },
        ),
    ]
