# Generated by Django 5.2.1 on 2025-09-17 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_initial'),
        ('trading', '0001_initial'),
        ('user', '0014_user_entity_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('VIEW_PROFILE', 'Ver perfil completo'), ('EDIT_PROFILE', 'Editar información básica'), ('TRADING_VIEW', 'Ver órdenes de trading'), ('TRADING_MANAGE', 'Gestionar órdenes de trading'), ('FULL_ACCESS', 'Acceso total temporal'), ('CREATE_PURCHASE_ORDER', 'Crear órdenes de compra'), ('CREATE_SALES_ORDER', 'Crear órdenes de venta'), ('CANCEL_ORDERS', 'Cancelar mis órdenes'), ('VIEW_ORDERS', 'Ver mis órdenes'), ('SELECT_MATCHES', 'Seleccionar matches para mis órdenes'), ('AUTO_SELECT_MATCHES', 'Permitir selección automática'), ('CANCEL_SELECTIONS', 'Cancelar selecciones de matches'), ('EXECUTE_PAYMENTS', 'Ejecutar pagos de mis órdenes'), ('VIEW_PAYMENT_STATUS', 'Ver estado de pagos'), ('TRADING_FULL_ACCESS', 'Acceso completo a trading'), ('FUND_SPECIFIC_ACCESS', 'Acceso específico a un fondo')], help_text='Tipo de permiso otorgado', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('REVOKED', 'Revocado')], default='ACTIVE', max_length=10)),
                ('reason', models.TextField(help_text='Motivo por el cual se otorga el permiso')),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo por orden (null = sin límite)', max_digits=15, null=True)),
                ('max_daily_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo diario (null = sin límite)', max_digits=15, null=True)),
                ('max_units_per_order', models.PositiveIntegerField(blank=True, help_text='Unidades máximas por orden (null = sin límite)', null=True)),
                ('auto_approve_under_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-aprobar órdenes menores a este monto', max_digits=15, null=True)),
                ('require_confirmation', models.BooleanField(default=True, help_text='Requiere confirmación del usuario antes de ejecutar')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Máximo número de usos (null = ilimitado)', null=True)),
                ('last_amount_used', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración del permiso')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(help_text='Admin que recibe el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, help_text='Fondo específico al que aplica (null = todos los fondos)', null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
                ('user', models.ForeignKey(help_text='Usuario que otorga el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario a Admin',
                'verbose_name_plural': 'Permisos de Usuario a Admin',
                'unique_together': {('user', 'admin_user', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='PermissionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('units', models.PositiveIntegerField(null=True)),
                ('success', models.BooleanField()),
                ('result_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.salesorder')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='user.useradminpermission')),
            ],
            options={
                'indexes': [models.Index(fields=['permission', 'executed_at'], name='user_permis_permiss_0fa1be_idx'), models.Index(fields=['action_type', 'success'], name='user_permis_action__5c119f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingPermissionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_description', models.TextField()),
                ('action_data', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(null=True)),
                ('user_response', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useradminpermission')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='user_pendin_status_4521a8_idx'), models.Index(fields=['permission', 'requested_at'], name='user_pendin_permiss_ee45a2_idx')],
            },
        ),
    ]
