# Generated by Django 5.2.4 on 2025-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_useradminpermission_auto_approve_under_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradminpermission',
            name='permission_type',
            field=models.CharField(choices=[('VIEW_PROFILE', 'Ver perfil completo'), ('EDIT_PROFILE', 'Editar información básica'), ('TRADING_VIEW', 'Ver órdenes de trading'), ('TRADING_MANAGE', 'Gestionar órdenes de trading'), ('FULL_ACCESS', 'Acceso total temporal'), ('CREATE_PURCHASE_ORDER', 'Crear órdenes de compra'), ('CREATE_SALES_ORDER', 'Crear órdenes de venta'), ('CANCEL_ORDERS', 'Cancelar mis órdenes'), ('VIEW_ORDERS', 'Ver mis órdenes'), ('SELECT_MATCHES', 'Seleccionar matches para mis órdenes'), ('AUTO_SELECT_MATCHES', 'Permitir selección automática'), ('CANCEL_SELECTIONS', 'Cancelar selecciones de matches'), ('EXECUTE_PAYMENTS', 'Ejecutar pagos de mis órdenes'), ('VIEW_PAYMENT_STATUS', 'Ver estado de pagos'), ('TRADING_FULL_ACCESS', 'Acceso completo a trading'), ('FUND_SPECIFIC_ACCESS', 'Acceso específico a un fondo')], help_text='Tipo de permiso otorgado', max_length=50),
        ),
    ]
