# Generated by Django 5.2.1 on 2025-11-06 13:43

import apps.asset.models.core
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícono')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='Código del activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del activo')),
                ('description', models.TextField(verbose_name='Descripción del activo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('sold', 'Vendido'), ('inactive', 'Inactivo')], default='draft', max_length=20, verbose_name='Estado')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('total_area_m2', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área total (m²)')),
                ('built_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área construida (m²)')),
                ('rentable_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área arrendable (m²)')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de construcción')),
                ('property_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula inmobiliaria')),
                ('cadastral_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cédula catastral')),
                ('title_deed_document', models.FileField(blank=True, null=True, upload_to=apps.asset.models.core.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Escritura pública')),
                ('property_certificate', models.FileField(blank=True, null=True, upload_to=apps.asset.models.core.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificado de tradición y libertad')),
                ('acquisition_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor de adquisición (COP)')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor actual de mercado (COP)')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de adquisición')),
                ('last_appraisal_date', models.DateField(blank=True, null=True, verbose_name='Fecha último avalúo')),
                ('appraisal_document', models.FileField(blank=True, null=True, upload_to=apps.asset.models.core.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento de avalúo')),
                ('is_leased', models.BooleanField(default=False, verbose_name='¿Está arrendado?')),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del arrendatario')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Renta mensual actual (COP)')),
                ('lease_start_date', models.DateField(blank=True, null=True, verbose_name='Inicio del contrato')),
                ('lease_end_date', models.DateField(blank=True, null=True, verbose_name='Fin del contrato')),
                ('lease_contract', models.FileField(blank=True, null=True, upload_to=apps.asset.models.core.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Contrato de arrendamiento')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.asset.models.core.asset_file_path, verbose_name='Imagen principal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fund.fund', verbose_name='Fondo asociado')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset.assettype', verbose_name='Tipo de activo')),
            ],
            options={
                'verbose_name': 'Activo Inmobiliario',
                'verbose_name_plural': 'Activos Inmobiliarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=apps.asset.models.core.asset_file_path, verbose_name='Imagen')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='asset.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen del Activo',
                'verbose_name_plural': 'Imágenes del Activo',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetOperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de período')),
                ('period_year', models.PositiveIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes (1-12)')),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trimestre (1-4)')),
                ('total_operating_expense', models.DecimalField(decimal_places=2, help_text='Suma total de todos los gastos operativos del período (mantenimiento, administración, impuestos, seguros, servicios)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total gastos operativos (COP)')),
                ('maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mantenimiento (COP)')),
                ('administration', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Administración (COP)')),
                ('property_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Impuestos prediales (COP)')),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Seguros (COP)')),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Servicios públicos (COP)')),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Otros gastos (COP)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_expenses', to='asset.asset', verbose_name='Activo')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_operating_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto Operativo del Activo',
                'verbose_name_plural': 'Gastos Operativos del Activo',
                'ordering': ['-period_year', '-period_month', '-created_at'],
                'unique_together': {('asset', 'period_type', 'period_year', 'period_month', 'period_quarter')},
            },
        ),
        migrations.CreateModel(
            name='AssetOperatingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de período')),
                ('period_year', models.PositiveIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes (1-12)')),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trimestre (1-4)')),
                ('total_operating_income', models.DecimalField(decimal_places=2, help_text='Suma total de todos los ingresos operativos del período', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total ingresos operativos (COP)')),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos por arrendamiento (COP)')),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Otros ingresos (COP)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_incomes', to='asset.asset', verbose_name='Activo')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_operating_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ingreso Operativo del Activo',
                'verbose_name_plural': 'Ingresos Operativos del Activo',
                'ordering': ['-period_year', '-period_month', '-created_at'],
                'unique_together': {('asset', 'period_type', 'period_year', 'period_month', 'period_quarter')},
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_code'], name='asset_asset_asset_c_17d610_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['fund', 'status'], name='asset_asset_fund_id_b64970_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['created_at'], name='asset_asset_created_839fef_idx'),
        ),
    ]
