# Generated by Django 5.2.1 on 2025-11-07 06:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetoperatingexpense',
            name='capex',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Gastos de capital: mejoras mayores, remodelaciones, equipamiento nuevo, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='CAPEX - Gastos de capital (COP)'),
        ),
        migrations.AddField(
            model_name='assetoperatingexpense',
            name='debt_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Pago total de deuda del período (principal + intereses)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pago de deuda (COP)'),
        ),
        migrations.AddField(
            model_name='assetoperatingexpense',
            name='non_operating_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Gastos que no son necesarios para mantener el inmueble: 4x1000, bancarios, asset management fees, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gastos no operativos (COP)'),
        ),
        migrations.AddField(
            model_name='assetoperatingincome',
            name='non_operating_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Ingresos ocasionales: multas de arrendamiento, indemnizaciones, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos no operativos (COP)'),
        ),
    ]
