# Generated by Django 5.2.1 on 2026-03-18 22:02

import apps.utils.models.file_helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0023_remove_investmentapplication_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=126)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.academy_category_image_path)),
                ('color', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=126)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.academy_article_image_path)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='fund.fund')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
