# Generated by Django 5.2.1 on 2026-03-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('financial_institution', '0005_alter_financialinstitution_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='fund',
        ),
        migrations.AddField(
            model_name='articles',
            name='financial_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='financial_institution.financialinstitution'),
            preserve_default=False,
        ),
    ]
