# Generated by Django 5.2.1 on 2025-08-27 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la entidad')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
                ('institution_type', models.CharField(choices=[('fund_manager', 'Administradora de Fondos'), ('broker_dealer', 'Comisionista de Bolsa'), ('fiduciary', 'Fiduciaria'), ('insurance', 'Aseguradora'), ('bank', 'Banco'), ('pension_fund', 'Fondo de Pensiones')], max_length=20)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='financial_institution/logos/', verbose_name='Logo')),
                ('entity_code', models.CharField(max_length=50, unique=True, verbose_name='Código de la entidad')),
                ('established_date', models.DateField(verbose_name='Fecha de constitución')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Número de registro')),
                ('tax_id', models.CharField(max_length=50, verbose_name='ID Fiscal')),
                ('superfinanciera_code', models.CharField(max_length=20, unique=True, verbose_name='Código Superfinanciera')),
                ('license_number', models.CharField(max_length=50, verbose_name='Número de licencia')),
                ('license_expiry_date', models.DateField(verbose_name='Fecha de vencimiento de licencia')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('under_review', 'En Revisión'), ('inactive', 'Inactiva')], default='active', max_length=15)),
                ('max_funds_allowed', models.PositiveIntegerField(default=50, verbose_name='Máximo fondos permitidos')),
                ('requires_kyc_validation', models.BooleanField(default=True, verbose_name='Requiere validación KYC')),
                ('auto_approve_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Monto bajo el cual se auto-aprueban inversiones', max_digits=14, null=True, verbose_name='Umbral de auto-aprobación')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('indicative', models.CharField(blank=True, max_length=32, null=True, verbose_name='Indicativo telefónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL de webhook')),
                ('notification_email', models.EmailField(max_length=254, verbose_name='Email para notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_financial_institutions', to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_financial_institutions', to='cities_light.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_financial_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_financial_institutions', to='cities_light.region')),
            ],
            options={
                'verbose_name': 'Financial Institution',
                'verbose_name_plural': 'Instituciones Financieras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInstitutionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('additional_info', 'Información Adicional Requerida'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('requested_investor_profile', models.CharField(choices=[('retail', 'Minorista'), ('professional', 'Profesional'), ('high_net_worth', 'Alto Patrimonio')], default='retail', max_length=15)),
                ('requested_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto de inversión solicitado')),
                ('application_notes', models.TextField(blank=True, null=True, verbose_name='Notas de la aplicación')),
                ('kyc_documents', models.JSONField(default=dict, verbose_name='Documentos KYC presentados')),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_category', models.CharField(blank=True, choices=[('documentation', 'Documentación Incompleta'), ('information', 'Información Incorrecta'), ('compliance', 'Problemas de Cumplimiento'), ('fraud', 'Sospecha de Fraude'), ('policy', 'No Cumple Políticas Internas')], max_length=20, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('can_reapply_after', models.DateField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=60, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('source_application', models.CharField(default='devise_platform', max_length=50)),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='financial_institution.financialinstitution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_financial_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_institution_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Institution Application',
                'verbose_name_plural': 'Solicitudes a Instituciones Financieras',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInstitutionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('expired', 'Expirado'), ('revoked', 'Revocado')], default='active', max_length=15)),
                ('investor_profile', models.CharField(choices=[('retail', 'Minorista'), ('professional', 'Profesional'), ('high_net_worth', 'Alto Patrimonio')], max_length=15)),
                ('max_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allowed_fund_types', models.JSONField(default=list)),
                ('restricted_fund_types', models.JSONField(default=list)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('kyc_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aml_check_passed', models.BooleanField(default=False)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='financial_institution.financialinstitutionapplication')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_institution_approvals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Institution Approval',
                'verbose_name_plural': 'Aprobaciones a Instituciones Financieras',
                'ordering': ['-approval_date'],
            },
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['status', 'financial_institution'], name='financial_i_status_6694c2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['user', 'status'], name='financial_i_user_id_5deef1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['status'], name='financial_i_status_42d284_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['expiry_date'], name='financial_i_expiry__860434_idx'),
        ),
    ]
