# Generated by Django 5.2.1 on 2025-09-10 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la entidad')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
                ('institution_type', models.CharField(choices=[('fund_manager', 'Administradora de Fondos'), ('broker_dealer', 'Comisionista de Bolsa'), ('fiduciary', 'Fiduciaria'), ('insurance', 'Aseguradora'), ('bank', 'Banco'), ('pension_fund', 'Fondo de Pensiones')], max_length=20)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='financial_institution/logos/', verbose_name='Logo')),
                ('entity_code', models.CharField(max_length=50, unique=True, verbose_name='Código de la entidad')),
                ('established_date', models.DateField(verbose_name='Fecha de constitución')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Número de registro')),
                ('tax_id', models.CharField(max_length=50, verbose_name='ID Fiscal')),
                ('superfinanciera_code', models.CharField(max_length=20, unique=True, verbose_name='Código Superfinanciera')),
                ('license_number', models.CharField(max_length=50, verbose_name='Número de licencia')),
                ('license_expiry_date', models.DateField(verbose_name='Fecha de vencimiento de licencia')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('under_review', 'En Revisión'), ('inactive', 'Inactiva')], default='active', max_length=15)),
                ('max_funds_allowed', models.PositiveIntegerField(default=50, verbose_name='Máximo fondos permitidos')),
                ('requires_kyc_validation', models.BooleanField(default=True, verbose_name='Requiere validación KYC')),
                ('auto_approve_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Monto bajo el cual se auto-aprueban inversiones', max_digits=14, null=True, verbose_name='Umbral de auto-aprobación')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('indicative', models.CharField(blank=True, max_length=32, null=True, verbose_name='Indicativo telefónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL de webhook')),
                ('notification_email', models.EmailField(max_length=254, verbose_name='Email para notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_financial_institutions', to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_financial_institutions', to='cities_light.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_financial_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_financial_institutions', to='cities_light.region')),
            ],
            options={
                'verbose_name': 'Financial Institution',
                'verbose_name_plural': 'Instituciones Financieras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInstitutionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_investor_profile', models.CharField(choices=[('conservative', 'Conservador'), ('moderate', 'Moderado'), ('aggressive', 'Agresivo'), ('sophisticated', 'Sofisticado'), ('institutional', 'Institucional')], max_length=20, verbose_name='Perfil de Inversor Solicitado')),
                ('requested_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de Inversión Solicitado')),
                ('application_notes', models.TextField(blank=True, verbose_name='Notas de la Solicitud')),
                ('kyc_documents', models.JSONField(blank=True, default=dict, verbose_name='Documentos KYC')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('additional_info', 'Información Adicional Requerida'), ('pending_user_signature', 'Pendiente de Firma del Usuario'), ('under_review_final', 'En Revisión Final'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=30, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de Revisión')),
                ('accepts_terms_and_conditions', models.BooleanField(default=False, verbose_name='Acepta términos y condiciones')),
                ('accepts_risk_disclosure', models.BooleanField(default=False, verbose_name='Acepta declaración de riesgos')),
                ('confirms_information_accuracy', models.BooleanField(default=False, verbose_name='Confirma veracidad de la información')),
                ('authorizes_background_check', models.BooleanField(default=False, verbose_name='Autoriza verificación de antecedentes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Razón de Rechazo')),
                ('rejection_category', models.CharField(blank=True, choices=[('documentation', 'Documentación Incompleta'), ('financial_profile', 'Perfil Financiero No Cumple'), ('compliance', 'Incumplimiento Normativo'), ('fraud', 'Sospecha de Fraude'), ('capacity', 'Capacidad de Inversión Insuficiente'), ('other', 'Otros')], max_length=20, null=True, verbose_name='Categoría de Rechazo')),
                ('can_reapply_after', models.DateField(blank=True, null=True, verbose_name='Puede Volver a Aplicar Después De')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='financial_institution.financialinstitution', verbose_name='Institución Financiera')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fi_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fi_applications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Aplicante')),
            ],
            options={
                'verbose_name': 'Solicitud de Membresía FI',
                'verbose_name_plural': 'Solicitudes de Membresía FI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInstitutionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pre_approved', 'Pre-Aprobada'), ('pre_approved_with_changes', 'Pre-Aprobada con Cambios'), ('contract_sent', 'Contrato Enviado'), ('contract_signed', 'Contrato Firmado'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('expired', 'Expirada'), ('revoked', 'Revocada')], default='pre_approved', max_length=30, verbose_name='Estado de Aprobación')),
                ('investor_profile', models.CharField(choices=[('conservative', 'Conservador'), ('moderate', 'Moderado'), ('aggressive', 'Agresivo'), ('sophisticated', 'Sofisticado'), ('institutional', 'Institucional')], max_length=20, verbose_name='Perfil de Inversor Aprobado')),
                ('max_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Máximo de Inversión')),
                ('allowed_fund_types', models.JSONField(blank=True, default=list, verbose_name='Tipos de Fondos Permitidos')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación Final')),
                ('contract_url', models.URLField(blank=True, verbose_name='URL del Contrato')),
                ('contract_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Contrato Generado En')),
                ('contract_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Contrato Enviado En')),
                ('contract_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Contrato Firmado En')),
                ('contract_notes', models.TextField(blank=True, verbose_name='Notas del Contrato')),
                ('signature_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Firma')),
                ('user_signature_notes', models.TextField(blank=True, verbose_name='Notas de Firma del Usuario')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('conditions', models.TextField(blank=True, verbose_name='Condiciones Especiales')),
                ('terms_modified', models.BooleanField(default=False, verbose_name='Términos Modificados')),
                ('changes_summary', models.TextField(blank=True, verbose_name='Resumen de Cambios')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='Razón de Suspensión')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspendido En')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='financial_institution.financialinstitutionapplication', verbose_name='Solicitud')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_approvals_made', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_suspensions_made', to=settings.AUTH_USER_MODEL, verbose_name='Suspendido Por')),
            ],
            options={
                'verbose_name': 'Aprobación de Membresía FI',
                'verbose_name_plural': 'Aprobaciones de Membresía FI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['user', 'financial_institution', 'status'], name='financial_i_user_id_67af01_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['status', 'created_at'], name='financial_i_status_000b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['reviewed_by', 'reviewed_at'], name='financial_i_reviewe_a22b07_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['status', 'expiry_date'], name='financial_i_status_3d29e9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['approved_by', 'approval_date'], name='financial_i_approve_2f1def_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['investor_profile', 'status'], name='financial_i_investo_330628_idx'),
        ),
    ]
