# Generated by Django 5.2.1 on 2025-10-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('financial_institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinstitution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_financial_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='financialinstitution',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_financial_institutions', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='financialinstitutionapplication',
            name='financial_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='financial_institution.financialinstitution', verbose_name='Institución Financiera'),
        ),
        migrations.AddField(
            model_name='financialinstitutionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fi_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por'),
        ),
        migrations.AddField(
            model_name='financialinstitutionapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fi_applications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Aplicante'),
        ),
        migrations.AddField(
            model_name='financialinstitutionapproval',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='financial_institution.financialinstitutionapplication', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='financialinstitutionapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_approvals_made', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por'),
        ),
        migrations.AddField(
            model_name='financialinstitutionapproval',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_suspensions_made', to=settings.AUTH_USER_MODEL, verbose_name='Suspendido Por'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['user', 'financial_institution', 'status'], name='financial_i_user_id_67af01_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['status', 'created_at'], name='financial_i_status_000b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapplication',
            index=models.Index(fields=['reviewed_by', 'reviewed_at'], name='financial_i_reviewe_a22b07_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['status', 'expiry_date'], name='financial_i_status_3d29e9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['approved_by', 'approval_date'], name='financial_i_approve_2f1def_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstitutionapproval',
            index=models.Index(fields=['investor_profile', 'status'], name='financial_i_investo_330628_idx'),
        ),
    ]
