# Generated by Django 5.2.1 on 2025-10-21 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institution', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FIPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(choices=[('view_applications', 'Ver Solicitudes'), ('create_applications', 'Crear Solicitudes'), ('approve_applications', 'Aprobar Solicitudes'), ('reject_applications', 'Rechazar Solicitudes'), ('view_members', 'Ver Miembros'), ('manage_members', 'Gestionar Miembros'), ('view_funds', 'Ver Fondos'), ('create_funds', 'Crear Fondos'), ('manage_funds', 'Gestionar Fondos'), ('send_contracts', 'Enviar Contratos'), ('sign_contracts', 'Firmar Contratos'), ('view_reports', 'Ver Reportes'), ('export_data', 'Exportar Datos'), ('manage_groups', 'Gestionar Grupos'), ('manage_permissions', 'Gestionar Permisos')], max_length=100, unique=True, verbose_name='Código de permiso')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso FI',
                'verbose_name_plural': 'Permisos FI',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FICustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_groups', to='financial_institution.financialinstitution', verbose_name='Institución Financiera')),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='financial_institution.fipermission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Grupo Personalizado FI',
                'verbose_name_plural': 'Grupos Personalizados FI',
                'ordering': ['financial_institution', 'name'],
                'unique_together': {('financial_institution', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FIUserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fi_group_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='financial_institution.ficustomgroup', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fi_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de Usuario en Grupo FI',
                'verbose_name_plural': 'Membresías de Usuarios en Grupos FI',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'group', 'is_active'], name='financial_i_user_id_c43eb0_idx'), models.Index(fields=['group', 'is_active'], name='financial_i_group_i_e0a39b_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
