# Generated by Django 5.2.1 on 2025-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institution', '0003_fipermission_ficustomgroup_fiusergroupmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fipermission',
            options={'ordering': ['module', 'category', 'name'], 'verbose_name': 'Permiso FI', 'verbose_name_plural': 'Permisos FI'},
        ),
        migrations.AddField(
            model_name='fipermission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='fipermission',
            name='module',
            field=models.CharField(db_index=True, default='example', help_text='Módulo al que petenece (fi, fund, trading, etc)', max_length=100, verbose_name='Módulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fipermission',
            name='codename',
            field=models.CharField(help_text="Identificador único del permiso (ej: 'view_applications')", max_length=100, unique=True, verbose_name='Código de permiso'),
        ),
        migrations.AddIndex(
            model_name='fipermission',
            index=models.Index(fields=['module', 'category'], name='financial_i_module_0e15ae_idx'),
        ),
        migrations.AddIndex(
            model_name='fipermission',
            index=models.Index(fields=['codename', 'is_active'], name='financial_i_codenam_066c02_idx'),
        ),
    ]
