# Generated by Django 5.2.1 on 2026-02-11 21:32

import apps.utils.models.file_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institution', '0004_alter_fipermission_options_fipermission_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstitution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.fi_logo_path, verbose_name='Logo'),
        ),
    ]
