# Generated by Django 5.2.1 on 2025-10-21 12:03

import django.db.models.deletion
from django.db import migrations, models
from apps.utils.models.file_helpers import info_financial_certification_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('druo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('certification_file', models.FileField(upload_to=info_financial_certification_file_path)),
                ('aba_code', models.CharField(blank=True, max_length=64, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=64, null=True)),
                ('account_subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_type', to='druo.accountsubtype')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_type', to='druo.accounttype')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banking_entity', to='druo.bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
