# Generated by Django 3.2.18 on 2025-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='hd_wallet',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
