# Generated by Django 5.2.1 on 2025-09-17 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentransaction',
            name='trading_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.transaction'),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receipts', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['status', 'fund_type'], name='fund_fund_status_6b73c2_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['created_at'], name='fund_fund_created_ad2458_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['name'], name='fund_fund_name_3bd753_idx'),
        ),
        migrations.AddIndex(
            model_name='fundsemestraldocument',
            index=models.Index(fields=['fund', 'uploaded_date'], name='fund_fundse_fund_id_e2b2bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundtoken',
            unique_together={('fund', 'token_id')},
        ),
        migrations.AddIndex(
            model_name='investmentapplication',
            index=models.Index(fields=['application_status', 'created_at'], name='fund_invest_applica_e1d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentapplication',
            index=models.Index(fields=['fund', 'user'], name='fund_invest_fund_id_de661d_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentapplication',
            index=models.Index(fields=['user', 'application_status'], name='fund_invest_user_id_9fbb05_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['investment_status', 'created_at'], name='fund_fundin_investm_2e09cd_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['created_at'], name='fund_fundin_created_ce59db_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['maturity_date'], name='fund_fundin_maturit_7ff88c_idx'),
        ),
    ]
