# Generated by Django 5.2.1 on 2025-10-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_institution', '0001_initial'),
        ('fund', '0001_initial'),
        ('kaleido', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionperiod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='financial_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_institution.financialinstitution', verbose_name='Institución financiera'),
        ),
        migrations.AddField(
            model_name='fund',
            name='hd_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaleido.wallet', verbose_name='Wallet HD'),
        ),
        migrations.AddField(
            model_name='fund',
            name='token_contract_721',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaleido.instanceoftokencontract721', verbose_name='Contrato de Token 721'),
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_core', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
        ),
        migrations.AddField(
            model_name='distributionperiod',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_periods', to='fund.fund', verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fund_investments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='fundpricehistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundpricehistory',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='fundsemestraldocument',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestral_documents', to='fund.fund', verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='fundsemestraldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='fund_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='fund.fundinvestment', verbose_name='Inversión asociada'),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='owner_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='contract_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_fund_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Contrato enviado por'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fund.fund', verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_fund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_fund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_fund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment', to='fund.investmentapplication', verbose_name='Solicitud origen'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='distribution_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_records', to='fund.distributionperiod'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='fund.fundinvestment'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contracts', to='fund.fund', verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='tokendistributiondetail',
            name='investment_distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_details', to='fund.investmentdistributionrecord'),
        ),
        migrations.AddField(
            model_name='tokendistributiondetail',
            name='owner_on_record_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Propietario en fecha de registro'),
        ),
        migrations.AddField(
            model_name='tokendistributiondetail',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_details', to='fund.fundtoken'),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='token_transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_transactions', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='token_transactions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fund.fundtoken'),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='trading_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.transaction'),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receipts', to='fund.fund'),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['status', 'fund_type'], name='fund_fund_status_6b73c2_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['created_at'], name='fund_fund_created_ad2458_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['name'], name='fund_fund_name_3bd753_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionperiod',
            index=models.Index(fields=['fund', 'status'], name='fund_distri_fund_id_3e5555_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionperiod',
            index=models.Index(fields=['record_date', 'status'], name='fund_distri_record__25eddc_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionperiod',
            index=models.Index(fields=['payment_date'], name='fund_distri_payment_001ec9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distributionperiod',
            unique_together={('fund', 'period_year', 'period_month', 'distribution_type')},
        ),
        migrations.AddIndex(
            model_name='fundsemestraldocument',
            index=models.Index(fields=['fund', 'uploaded_date'], name='fund_fundse_fund_id_e2b2bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundtoken',
            unique_together={('fund', 'token_id')},
        ),
        migrations.AddIndex(
            model_name='investmentapplication',
            index=models.Index(fields=['application_status', 'created_at'], name='fund_invest_applica_e1d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentapplication',
            index=models.Index(fields=['fund', 'user'], name='fund_invest_fund_id_de661d_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentapplication',
            index=models.Index(fields=['user', 'application_status'], name='fund_invest_user_id_9fbb05_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['investment_status', 'created_at'], name='fund_fundin_investm_2e09cd_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['created_at'], name='fund_fundin_created_ce59db_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['maturity_date'], name='fund_fundin_maturit_7ff88c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentdistributionrecord',
            unique_together={('distribution_period', 'investment')},
        ),
        migrations.AddIndex(
            model_name='tokendistributiondetail',
            index=models.Index(fields=['token', 'investment_distribution'], name='fund_tokend_token_i_9383f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tokendistributiondetail',
            index=models.Index(fields=['owner_on_record_date', 'investment_distribution'], name='fund_tokend_owner_o_b07d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokendistributiondetail',
            unique_together={('investment_distribution', 'token')},
        ),
    ]
