# Generated by Django 5.2.1 on 2025-09-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institution', '0001_initial'),
        ('fund', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='financial_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_institution.financialinstitution', verbose_name='Institución financiera'),
        ),
    ]
