# Generated by Django 3.2.18 on 2025-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fund_hd_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='hd_wallet',
            field=models.CharField(default='', max_length=100),
        ),
    ]
