# Generated by Django 5.2.1 on 2025-11-11 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='initial_unit_value',
            new_name='initial_price_per_unit',
        ),
        migrations.AddField(
            model_name='fund',
            name='acquisition_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total de compra/adquisición de los activos del fondo', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de adquisición del fondo (COP)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='rentable_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma del área arrendable de todos los activos del fondo', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Área arrendable (m²)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='total_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma del área total de todos los activos del fondo', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Área total (m²)'),
        ),
    ]
