# Generated by Django 5.2.1 on 2025-09-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fund_financial_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='units_owned',
            field=models.IntegerField(default=0, verbose_name='Unidades poseídas'),
        ),
    ]
