# Generated by Django 5.2.1 on 2025-11-11 15:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_rename_initial_unit_value_fund_initial_price_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundOperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de período')),
                ('period_year', models.PositiveIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes (1-12)')),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trimestre (1-4)')),
                ('total_operating_expense', models.DecimalField(decimal_places=2, help_text='Suma total de todos los gastos operativos del período', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total gastos operativos (COP)')),
                ('maintenance', models.DecimalField(blank=True, decimal_places=2, help_text='Mantenimiento preventivo y correctivo de activos', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mantenimiento (COP)')),
                ('administration', models.DecimalField(blank=True, decimal_places=2, help_text='Gastos de administración de propiedades', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Administración (COP)')),
                ('property_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Impuestos prediales (COP)')),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, help_text='Seguros de los activos del fondo', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Seguros (COP)')),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, help_text='Agua, luz, gas, aseo, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Servicios públicos (COP)')),
                ('security', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Seguridad (COP)')),
                ('legal_accounting', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Legal y contabilidad (COP)')),
                ('asset_management_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Comisión de administración del fondo', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Asset Management Fee (COP)')),
                ('property_management_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Comisión de gestión de propiedades', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Property Management Fee (COP)')),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Otros gastos operativos (COP)')),
                ('non_operating_expenses', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='4x1000, bancarios, multas, intereses no relacionados con deuda, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gastos no operativos (COP)')),
                ('capex', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Mejoras mayores, remodelaciones, equipamiento nuevo, expansiones', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='CAPEX - Gastos de capital (COP)')),
                ('debt_principal_payment', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Amortización de capital de préstamos', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pago de principal de deuda (COP)')),
                ('debt_interest_payment', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Intereses pagados sobre préstamos', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pago de intereses de deuda (COP)')),
                ('expense_breakdown_by_asset', models.JSONField(blank=True, default=dict, help_text='Diccionario con asset_id: monto para trazabilidad', verbose_name='Desglose por activo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_expenses', to='fund.fund', verbose_name='Fondo')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fund_operating_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_fund_operating_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Gasto Operativo del Fondo',
                'verbose_name_plural': 'Gastos Operativos del Fondo',
                'ordering': ['-period_year', '-period_month', '-created_at'],
                'indexes': [models.Index(fields=['fund', 'period_year', 'period_month'], name='fund_fundop_fund_id_e12a8a_idx'), models.Index(fields=['period_type', 'period_year'], name='fund_fundop_period__94e6b2_idx')],
                'unique_together': {('fund', 'period_type', 'period_year', 'period_month', 'period_quarter')},
            },
        ),
        migrations.CreateModel(
            name='FundOperatingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de período')),
                ('period_year', models.PositiveIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes (1-12)')),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trimestre (1-4)')),
                ('total_operating_income', models.DecimalField(decimal_places=2, help_text='Suma total de todos los ingresos operativos del período', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total ingresos operativos (COP)')),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, help_text='Suma de rentas de todos los activos del fondo', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos por arrendamiento (COP)')),
                ('parking_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos por parqueaderos (COP)')),
                ('storage_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos por bodegas (COP)')),
                ('amenities_income', models.DecimalField(blank=True, decimal_places=2, help_text='Salones de eventos, gimnasio, co-working, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos por amenidades (COP)')),
                ('late_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Multas por mora (COP)')),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Otros ingresos operativos (COP)')),
                ('non_operating_income', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Ingresos ocasionales: indemnizaciones, intereses bancarios, venta de activos, etc.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos no operativos (COP)')),
                ('income_breakdown_by_asset', models.JSONField(blank=True, default=dict, help_text='Diccionario con asset_id: monto para trazabilidad', verbose_name='Desglose por activo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_incomes', to='fund.fund', verbose_name='Fondo')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fund_operating_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_fund_operating_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Ingreso Operativo del Fondo',
                'verbose_name_plural': 'Ingresos Operativos del Fondo',
                'ordering': ['-period_year', '-period_month', '-created_at'],
                'indexes': [models.Index(fields=['fund', 'period_year', 'period_month'], name='fund_fundop_fund_id_4b21c1_idx'), models.Index(fields=['period_type', 'period_year'], name='fund_fundop_period__50270d_idx')],
                'unique_together': {('fund', 'period_type', 'period_year', 'period_month', 'period_quarter')},
            },
        ),
    ]
