# Generated by Django 5.2.1 on 2025-11-21 05:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_fundoperatingexpense_fundoperatingincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoperatingexpense',
            name='non_operating_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingresos no operativos (COP)'),
        ),
    ]
