# Generated by Django 5.2.1 on 2025-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_alter_fundinvestment_units_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='current_unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor actual por unidad'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='purchase_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra por unidad'),
        ),
    ]
