# Generated by Django 3.2.18 on 2025-02-12 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0004_auto_20250204_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='investors',
            field=models.ManyToManyField(blank=True, null=True, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
    ]
