# Generated by Django 5.2.1 on 2025-09-30 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_alter_fundinvestment_current_unit_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinvestment',
            name='pending_dividends',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='realized_capital_gains',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='total_dividends_received',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='unrealized_capital_gains',
        ),
        migrations.AddField(
            model_name='fund',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión por unidad', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='tkn_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del token mas comisiones'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_core', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
        ),
    ]
