# Generated by Django 3.2.18 on 2025-02-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0005_fund_investors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='investors',
        ),
        migrations.CreateModel(
            name='FundInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='fund.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
