# Generated by Django 5.2.1 on 2025-11-21 06:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_fundoperatingexpense_non_operating_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='acquisition_value',
        ),
        migrations.AddField(
            model_name='fund',
            name='initial_capex',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total de compra/inversion total del fondo', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de compra o inversion'),
        ),
    ]
