# Generated by Django 5.2.1 on 2025-09-30 20:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_remove_fundinvestment_pending_dividends_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annually', 'Semestral'), ('annually', 'Anual'), ('extraordinary', 'Extraordinaria')], default='monthly', max_length=20)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField(blank=True, null=True)),
                ('period_quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('total_distribution_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto total a distribuir')),
                ('net_operating_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ingreso operativo neto del período')),
                ('distribution_yield_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Porcentaje de rendimiento distribuido')),
                ('total_tokens_outstanding', models.PositiveIntegerField(verbose_name='Total tokens en circulación')),
                ('distribution_per_token', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Distribución por token')),
                ('record_date', models.DateField(verbose_name='Fecha de registro (snapshot de propietarios)')),
                ('ex_dividend_date', models.DateField(verbose_name='Fecha ex-dividendo')),
                ('payment_date', models.DateField(verbose_name='Fecha de pago programada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_approval', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('distribution_notes', models.TextField(blank=True)),
                ('calculation_metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_distributions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_periods', to='fund.fund', verbose_name='Fondo')),
            ],
            options={
                'verbose_name': 'Período de Distribución',
                'verbose_name_plural': 'Períodos de Distribución',
                'ordering': ['-period_year', '-period_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentDistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('tokens_held_on_record_date', models.PositiveIntegerField(verbose_name='Tokens poseídos en fecha de registro')),
                ('token_ids_snapshot', models.JSONField(help_text='Lista de token_ids que poseía en la fecha de registro', verbose_name='IDs de tokens específicos')),
                ('distribution_per_token', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Distribución por token aplicada')),
                ('gross_distribution_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto bruto de distribución')),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retención en la fuente')),
                ('net_distribution_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto neto a pagar')),
                ('participation_percentage', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Porcentaje de participación')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('calculated', 'Calculado'), ('processing', 'Procesando Pago'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('reinvested', 'Reinvertido')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia Bancaria'), ('reinvestment', 'Reinversión Automática'), ('digital_wallet', 'Billetera Digital'), ('check', 'Cheque'), ('other', 'Otro')], max_length=30, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha efectiva de pago')),
                ('calculation_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos de cálculo')),
                ('payment_notes', models.TextField(blank=True)),
                ('distribution_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_records', to='fund.distributionperiod')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='fund.fundinvestment')),
            ],
            options={
                'verbose_name': 'Registro de Distribución por Inversión',
                'verbose_name_plural': 'Registros de Distribución por Inversión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenDistributionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('token_nickname', models.CharField(max_length=255)),
                ('distribution_amount', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Monto distribuido a este token')),
                ('days_held_in_period', models.PositiveIntegerField(verbose_name='Días poseído en el período')),
                ('acquisition_date', models.DateTimeField(verbose_name='Fecha de adquisición del token')),
                ('calculation_notes', models.TextField(blank=True)),
                ('investment_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_details', to='fund.investmentdistributionrecord')),
                ('owner_on_record_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Propietario en fecha de registro')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_details', to='fund.fundtoken')),
            ],
            options={
                'verbose_name': 'Detalle de Distribución por Token',
                'verbose_name_plural': 'Detalles de Distribución por Token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='distributionperiod',
            index=models.Index(fields=['fund', 'status'], name='fund_distri_fund_id_3e5555_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionperiod',
            index=models.Index(fields=['record_date', 'status'], name='fund_distri_record__25eddc_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionperiod',
            index=models.Index(fields=['payment_date'], name='fund_distri_payment_001ec9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distributionperiod',
            unique_together={('fund', 'period_year', 'period_month', 'distribution_type')},
        ),
        migrations.AddIndex(
            model_name='investmentdistributionrecord',
            index=models.Index(fields=['investment', 'payment_status'], name='fund_invest_investm_48e54f_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentdistributionrecord',
            index=models.Index(fields=['distribution_period', 'payment_status'], name='fund_invest_distrib_b125ab_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentdistributionrecord',
            index=models.Index(fields=['payment_date'], name='fund_invest_payment_b6aef0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentdistributionrecord',
            unique_together={('distribution_period', 'investment')},
        ),
        migrations.AddIndex(
            model_name='tokendistributiondetail',
            index=models.Index(fields=['token', 'investment_distribution'], name='fund_tokend_token_i_9383f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tokendistributiondetail',
            index=models.Index(fields=['owner_on_record_date', 'investment_distribution'], name='fund_tokend_owner_o_b07d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokendistributiondetail',
            unique_together={('investment_distribution', 'token')},
        ),
    ]
