# Generated by Django 5.2.1 on 2025-11-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_remove_fund_acquisition_value_fund_initial_capex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundoperatingexpense',
            name='non_operating_income',
        ),
    ]
