# Generated by Django 5.2.1 on 2025-10-03 00:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_distributionperiod_investmentdistributionrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investmentdistributionrecord',
            name='fund_invest_investm_48e54f_idx',
        ),
        migrations.RemoveIndex(
            model_name='investmentdistributionrecord',
            name='fund_invest_distrib_b125ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='investmentdistributionrecord',
            name='fund_invest_payment_b6aef0_idx',
        ),
        migrations.RemoveField(
            model_name='investmentdistributionrecord',
            name='distribution_per_token',
        ),
        migrations.RemoveField(
            model_name='investmentdistributionrecord',
            name='gross_distribution_amount',
        ),
        migrations.RemoveField(
            model_name='investmentdistributionrecord',
            name='net_distribution_amount',
        ),
        migrations.RemoveField(
            model_name='investmentdistributionrecord',
            name='withholding_tax',
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='cop_to_token_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Tokens por cada peso COP', max_digits=12, null=True, verbose_name='Tasa de cambio COP a tokens'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='distribution_type',
            field=models.CharField(choices=[('cop_amount', 'Monto en COP'), ('token_transfer', 'Transferencia de Tokens')], default='cop_amount', max_length=20, verbose_name='Tipo de distribución'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='equivalent_tokens_calculated',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Cantidad de tokens equivalente al monto COP', max_digits=18, null=True, verbose_name='Tokens equivalentes calculados'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='gross_distribution_amount_cop',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado en pesos colombianos', max_digits=14, null=True, verbose_name='Monto bruto distribución (COP)'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='net_distribution_amount_cop',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto neto a distribuir en pesos colombianos', max_digits=14, null=True, verbose_name='Monto neto distribución (COP)'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='remaining_cop_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en COP que no se pudo convertir a tokens enteros', max_digits=14, null=True, verbose_name='Monto COP remanente'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='tokens_to_transfer',
            field=models.IntegerField(blank=True, help_text='Número entero de tokens que se transferirán', null=True, verbose_name='Tokens a transferir'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas de verificación'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='investmentdistributionrecord',
            name='withholding_tax_cop',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Retención en la fuente (COP)'),
        ),
        migrations.AlterField(
            model_name='investmentdistributionrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cop_transfer', 'Transferencia COP'), ('token_transfer', 'Transferencia de Tokens'), ('bank_transfer', 'Transferencia Bancaria'), ('digital_wallet', 'Billetera Digital'), ('mixed', 'Mixto'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investmentdistributionrecord',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('calculated', 'Calculado'), ('verified', 'Verificado'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('reinvested', 'Reinvertido')], default='calculated', max_length=20),
        ),
    ]
