# Generated by Django 3.2.18 on 2025-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_transferreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
