# Generated by Django 5.2.1 on 2025-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_remove_investmentdistributionrecord_fund_invest_investm_48e54f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionperiod',
            name='distribution_per_token',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Distribución por token'),
        ),
        migrations.AlterField(
            model_name='distributionperiod',
            name='distribution_yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Porcentaje de rendimiento distribuido'),
        ),
    ]
