# Generated by Django 3.2.18 on 2025-02-18 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0008_fund_secret'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundinvestment',
            unique_together={('fund', 'investor')},
        ),
    ]
