# Generated by Django 5.2.1 on 2025-12-19 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_receiptype_remove_fund_current_annual_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='mercantile_trust_agreement',
            field=models.FileField(blank=True, help_text='Documento de contrato de fiducia mercantil', null=True, upload_to='funds/mercantile_trust_agreement/', verbose_name='Contrato de fiducia mercantil'),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('doc_transfer', models.FileField(blank=True, null=True, upload_to='funds/transfer/', verbose_name='Documento de cesion')),
                ('effective_date', models.DateField(verbose_name='Fecha de vigencia')),
                ('class_transfer', models.CharField(max_length=40, verbose_name='Clase de sesion que se adquirio')),
                ('settlor', models.CharField(max_length=40, verbose_name='Actor que cede su participacion')),
                ('assignee', models.CharField(max_length=40, verbose_name='Actor que recibe la participacion')),
                ('assigned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad que se acuerda entre las partes')),
                ('actor_settlor', models.CharField(max_length=50, verbose_name='Representante legal del al entidad Cesionario')),
                ('actor_assignee', models.CharField(max_length=50, verbose_name='Representante legal de la entidad Cedente')),
                ('nit_settlor', models.IntegerField(verbose_name='Nit del actor que cede si participacion')),
                ('nit_assignee', models.IntegerField(verbose_name='Nit del actor que recibe la participacion')),
                ('type_doc_settlor', models.CharField(choices=[('national identity card', 'cedula de ciudadania'), ('foreigners identity card', 'cedula de extranjeria')], max_length=50, verbose_name='Tipo de documento del representante legal del Cesionario')),
                ('type_doc_assignee', models.CharField(choices=[('national identity card', 'cedula de ciudadania'), ('foreigners identity card', 'cedula de extranjeria')], max_length=50, verbose_name='Tipo de documento del representante legal del Cedente')),
                ('id_doc_settlor', models.IntegerField(verbose_name='Numero de documento del representante legal del Cesionario')),
                ('id_doc_assignee', models.IntegerField(verbose_name='Numero de documento del representante legal del Cedente')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fund.fund', verbose_name='Fondo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], max_length=20, verbose_name='Tipo de período')),
                ('period_year', models.PositiveIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, help_text='Requerido para períodos mensuales', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('document', models.FileField(upload_to='funds/accountability/%Y/', verbose_name='Documento aprobado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountability_docs', to='fund.fund', verbose_name='Fondo')),
            ],
            options={
                'verbose_name': 'Rendición de Cuentas',
                'verbose_name_plural': 'Rendiciones de Cuentas',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('fund', 'period_type', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='OthersI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('doc_number', models.CharField(help_text='Ej: No.1, No.2', max_length=100, verbose_name='Número del documento')),
                ('name', models.CharField(help_text='Descripción breve del contenido', max_length=255, verbose_name='Nombre del otrosí')),
                ('document', models.FileField(upload_to='funds/othersi/', verbose_name='Documento')),
                ('description', models.TextField(blank=True, help_text='Detalle de las modificaciones incluidas', null=True, verbose_name='Descripción')),
                ('effective_date', models.DateField(blank=True, help_text='Fecha desde la cual aplica el otrosí', null=True, verbose_name='Fecha de vigencia')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='othersi', to='fund.fund', verbose_name='Fondo')),
            ],
            options={
                'verbose_name': 'Otrosí',
                'verbose_name_plural': 'Otrosíes',
                'ordering': ['fund', 'doc_number'],
                'unique_together': {('fund', 'doc_number')},
            },
        ),
    ]
