# Generated by Django 3.2.18 on 2025-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_alter_fundinvestment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='token_contract_721',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
