# Generated by Django 5.2.1 on 2025-12-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_fund_mercantile_trust_agreement_transfers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='type_doc_assignee',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería')], max_length=50, verbose_name='Tipo de documento del representante legal del Cedente'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='type_doc_settlor',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería')], max_length=50, verbose_name='Tipo de documento del representante legal del Cesionario'),
        ),
    ]
