# Generated by Django 5.2.1 on 2025-12-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_alter_transfers_type_doc_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='id_doc_assignee',
            field=models.BigIntegerField(verbose_name='Numero de documento del representante legal del Cedente'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='id_doc_settlor',
            field=models.BigIntegerField(verbose_name='Numero de documento del representante legal del Cesionario'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='nit_assignee',
            field=models.BigIntegerField(verbose_name='Nit del actor que recibe la participacion'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='nit_settlor',
            field=models.BigIntegerField(verbose_name='Nit del actor que cede si participacion'),
        ),
    ]
