# Generated by Django 3.2.18 on 2025-02-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_fund_token_contract_721'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='token_contract_721_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='token_contract_721_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
