# Generated by Django 5.2.1 on 2026-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0011_alter_transfers_id_doc_assignee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptype',
            options={'ordering': ['code'], 'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'Tipos de Comprobantes'},
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cesion', 'verbose_name_plural': 'Cesiones'},
        ),
        migrations.AlterField(
            model_name='transfers',
            name='nit_settlor',
            field=models.BigIntegerField(verbose_name='Nit del actor que cede su participacion'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptype',
            unique_together={('code',)},
        ),
    ]
