# Generated by Django 3.2.18 on 2025-02-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0013_remove_instanceoftokencontract721_instance_id'),
        ('fund', '0011_auto_20250224_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='token_contract_721',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaleido.instanceoftokencontract721'),
        ),
    ]
