# Generated by Django 5.2.1 on 2026-01-20 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0012_alter_receiptype_options_alter_transfers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('agreement_type', models.CharField(choices=[('administration', 'Administración'), ('payments', 'Pagos'), ('other', 'Otro')], max_length=50)),
                ('trust_code', models.CharField(blank=True, max_length=100, null=True)),
                ('trust_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trust_nit', models.CharField(blank=True, max_length=50, null=True)),
                ('trustor_name', models.CharField(help_text='Nombre del fideicomitente', max_length=255)),
                ('trustor_nit', models.CharField(help_text='NIT del fideicomitente', max_length=50)),
                ('trustor_legal_representative', models.CharField(help_text='Representante legal del fideicomitente', max_length=255)),
                ('trustor_document_id', models.CharField(help_text='Documento de identidad del representante legal', max_length=50)),
                ('trustee_name', models.CharField(help_text='Nombre de la fiduciaria', max_length=255)),
                ('trustee_nit', models.CharField(help_text='NIT de la fiduciaria', max_length=50)),
                ('trustee_legal_representative', models.CharField(help_text='Representante legal de la fiduciaria', max_length=255)),
                ('beneficiary_name', models.CharField(help_text='Nombre del acreedor', max_length=255)),
                ('beneficiary_document_id', models.CharField(help_text='Documento de identidad del acreedor', max_length=50)),
                ('beneficiary_country', models.CharField(help_text='País del acreedor', max_length=100)),
                ('construction_date', models.DateField(blank=True, help_text='Fecha de constitución del contrato', null=True)),
                ('effective_date', models.DateField(help_text='Fecha de inicio de vigencia del contrato')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de expiración del contrato', null=True)),
                ('approved_loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto credito aprobado', max_digits=18, null=True)),
                ('currency', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('COP', 'Peso Colombiano')], default='COP', max_length=10)),
                ('signed_document_url', models.FileField(blank=True, help_text='Documento firmado del contrato fiduciario', null=True, upload_to='funds/trust_agreements/signed_documents/')),
                ('electronic_envelope', models.FileField(blank=True, help_text='Sobre electrónico del contrato fiduciario', null=True, upload_to='funds/trust_agreements/electronic_envelopes/')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_agreements', to='fund.fund')),
            ],
            options={
                'verbose_name': 'Contrato fiduciario',
                'verbose_name_plural': 'Contratos fiduciarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
