# Generated by Django 3.2.18 on 2025-02-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0012_alter_fund_token_contract_721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='token_contract_721_name',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='token_contract_721_symbol',
        ),
    ]
