# Generated by Django 3.2.18 on 2025-03-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0013_auto_20250225_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
