# Generated by Django 5.2.1 on 2026-01-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0013_trustagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de factura')),
                ('invoice_type', models.CharField(choices=[('sale', 'Venta'), ('comission', 'Comisión'), ('spent', 'Gasto')], max_length=20, verbose_name='Tipo de factura')),
                ('issuer_name', models.CharField(max_length=255, verbose_name='Nombre del emisor')),
                ('issuer_nit', models.CharField(max_length=50, verbose_name='NIT del emisor')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='Nombre del receptor')),
                ('receiver_nit', models.CharField(max_length=50, verbose_name='NIT del receptor')),
                ('issued_date', models.DateField(verbose_name='Fecha de emisión')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('notion', models.TextField(verbose_name='Concepto')),
                ('items_details', models.JSONField(blank=True, default=list, help_text='Lista de ítems en formato JSON', verbose_name='Detalles de ítems')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal (COP)')),
                ('value_iva', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor IVA (COP)')),
                ('withholding_tax', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Retención en la fuente (COP)')),
                ('ica_withholding_tax', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Retención ICA (COP)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto total (COP)')),
                ('invoice_status', models.CharField(choices=[('issued', 'Emitida'), ('paid', 'Pagada'), ('expired', 'Vencida'), ('annulled', 'Anulada')], default='issued', max_length=20, verbose_name='Estado de la factura')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Monto pagado (COP)')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de pago')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='funds/invoices/%Y/', verbose_name='Documento de la factura')),
                ('xml_attachment', models.FileField(blank=True, null=True, upload_to='funds/invoices/xml/%Y/', verbose_name='Archivo XML de la factura')),
                ('accounting_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fund.account', verbose_name='Cuenta contable')),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fund.accountingperiod', verbose_name='Período contable')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fund.fund', verbose_name='Fondo')),
                ('trust_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fund.trustagreement', verbose_name='Acuerdo de fideicomiso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
