# Generated by Django 5.2.1 on 2026-01-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0014_invoicerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_category', 'account_id'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Cuentas Contables'},
        ),
        migrations.AlterModelOptions(
            name='invoicerecord',
            options={'ordering': ['-issued_date', '-created_at'], 'verbose_name': 'Registro de Factura', 'verbose_name_plural': 'Registros de Facturas'},
        ),
        migrations.AlterUniqueTogether(
            name='invoicerecord',
            unique_together={('fund', 'invoice_number')},
        ),
    ]
