# Generated by Django 3.2.18 on 2025-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0014_fund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
