# Generated by Django 5.2.1 on 2026-01-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0015_alter_account_options_alter_invoicerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fideicomiso', 'verbose_name_plural': 'Fideicomisos'},
        ),
    ]
