# Generated by Django 3.2.18 on 2025-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0015_fund_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='annual_return',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annualized return percentage', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='asset_composition',
            field=models.JSONField(blank=True, help_text='Percentage distribution by asset type', null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='dividend_distribution',
            field=models.CharField(blank=True, choices=[('automatic_reinvestment', 'Automatic Reinvestment'), ('periodic_distribution', 'Periodic Distribution'), ('mixed', 'Mixed')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='early_withdrawal_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Penalty percentage for early withdrawal', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('securities', 'Securities'), ('private_equity', 'Private Equity'), ('pension', 'Voluntary Pension'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='initial_unit_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='investment_horizon',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Recommended time in years', null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='main_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Management fee percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='minimum_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='number_of_investors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='operations_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='operations_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='permanence_period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum time in days', null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_profile',
            field=models.CharField(blank=True, choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_rating',
            field=models.CharField(blank=True, help_text='E.g.: AAA, AA+, BBB, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='success_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Performance fee percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='superintendency_registry',
            field=models.CharField(blank=True, help_text='Financial Superintendency registry number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='trading_hours',
            field=models.CharField(blank=True, help_text='E.g.: 8:00 a.m. - 1:00 p.m.', max_length=100, null=True),
        ),
    ]
