# Generated by Django 3.2.18 on 2025-05-05 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0016_auto_20250424_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Razón para el cambio de precio', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='fund.fund')),
            ],
            options={
                'verbose_name': 'Historial de Precio de Fondo',
                'verbose_name_plural': 'Historial de Precios de Fondos',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.DeleteModel(
            name='FundPrice',
        ),
    ]
