# Generated by Django 5.2.1 on 2026-02-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0016_alter_fund_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundinvestment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inversión en Fideicomiso', 'verbose_name_plural': 'Inversiones en Fideicomisos'},
        ),
        migrations.AlterModelOptions(
            name='fundtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de Fideicomiso', 'verbose_name_plural': 'Tokens de Fideicomisos'},
        ),
        migrations.AlterField(
            model_name='investmentapplication',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fund.fund', verbose_name='Fideicomiso'),
        ),
        migrations.AlterField(
            model_name='investmentapplication',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('insufficient_funds', 'Fondos Insuficientes'), ('invalid_documentation', 'Documentación Inválida'), ('risk_profile_mismatch', 'Perfil de Riesgo No Compatible'), ('regulatory_compliance', 'Cumplimiento Regulatorio'), ('investment_limits', 'Límites de Inversión'), ('fund_capacity', 'Capacidad del Fideicomiso'), ('other', 'Otro')], max_length=25, null=True, verbose_name='Categoría de rechazo'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contracts', to='fund.fund', verbose_name='Fideicomiso'),
        ),
    ]
