# Generated by Django 5.2.1 on 2026-02-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0017_alter_fundinvestment_options_alter_fundtoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Fondo',
                'verbose_name_plural': 'Categorías de Fondos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fund.fundcategory', verbose_name='Categoría del fondo'),
        ),
    ]
