# Generated by Django 3.2.18 on 2025-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0017_auto_20250505_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='funds/images/'),
        ),
    ]
