# Generated by Django 5.2.1 on 2026-02-11 21:32

import apps.utils.models.file_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0018_fundcategory_fund_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingimportbatch',
            name='file',
        ),
        migrations.AddField(
            model_name='accountingimportbatch',
            name='accounting_file',
            field=models.FileField(default='', upload_to=apps.utils.models.file_helpers.accounting_import_batch_file_path, verbose_name='Archivo XLSX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountability',
            name='document',
            field=models.FileField(upload_to=apps.utils.models.file_helpers.accountability_document_path, verbose_name='Documento aprobado'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.accounting_entry_attachment_path, verbose_name='Documento soporte'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='data_processing_policy',
            field=models.FileField(blank=True, help_text='Documento de política de tratamiento de datos', null=True, upload_to=apps.utils.models.file_helpers.fund_data_processing_policy_path, verbose_name='Política de tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fiduciary_draft',
            field=models.FileField(blank=True, help_text='Documento de Minuta Fiduciaria', null=True, upload_to=apps.utils.models.file_helpers.fund_fiduciary_draft_path, verbose_name='Minuta Fiduciaria'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.fund_image_path, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='image_admin',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.fund_image_admin_path, verbose_name='Imagen administrativa'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='mercantile_trust_agreement',
            field=models.FileField(blank=True, help_text='Documento de contrato de fiducia mercantil', null=True, upload_to=apps.utils.models.file_helpers.fund_mercantile_trust_agreement_path, verbose_name='Contrato de fiducia mercantil'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Otros documentos', null=True, upload_to=apps.utils.models.file_helpers.fund_other_documents_path, verbose_name='Otros documentos'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='terms_and_conditions',
            field=models.FileField(blank=True, help_text='Documento de términos y condiciones', null=True, upload_to=apps.utils.models.file_helpers.fund_terms_and_conditions_path, verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.fund_investment_payment_receipt_path, verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='fundsemestraldocument',
            name='document',
            field=models.FileField(upload_to=apps.utils.models.file_helpers.fund_semestral_document_path, verbose_name='Documento semestral'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.invoice_record_attachment_path, verbose_name='Documento de la factura'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='xml_attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.invoice_record_xml_attachment_path, verbose_name='Archivo XML de la factura'),
        ),
        migrations.AlterField(
            model_name='othersi',
            name='document',
            field=models.FileField(upload_to=apps.utils.models.file_helpers.othersi_document_path, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='doc_transfer',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.models.file_helpers.commission_transfer_doc_transfer_path, verbose_name='Documento de cesion'),
        ),
        migrations.AlterField(
            model_name='trustagreement',
            name='electronic_envelope',
            field=models.FileField(blank=True, help_text='Sobre electrónico del contrato fiduciario', null=True, upload_to=apps.utils.models.file_helpers.trust_agreement_electronic_envelope_path),
        ),
        migrations.AlterField(
            model_name='trustagreement',
            name='signed_document_url',
            field=models.FileField(blank=True, help_text='Documento firmado del contrato fiduciario', null=True, upload_to=apps.utils.models.file_helpers.trust_agreement_signed_document_path),
        ),
    ]
