# Generated by Django 3.2.18 on 2025-05-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0018_fund_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de unidades del fondo'),
        ),
    ]
