# Generated by Django 3.2.18 on 2025-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0019_alter_fund_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='amount',
            new_name='amount_units',
        ),
        migrations.AddField(
            model_name='fund',
            name='amount_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de tokens del fondo'),
        ),
    ]
