# Generated by Django 5.2.1 on 2026-02-18 16:48

import apps.utils.models.file_helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0019_remove_accountingimportbatch_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSemestralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del tipo de documento')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del tipo de documento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento Semestral',
                'verbose_name_plural': 'Tipos de Documentos Semestrales',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='fund',
            name='other_documents',
        ),
        migrations.RemoveField(
            model_name='fundsemestraldocument',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='fundsemestraldocument',
            name='year',
        ),
        migrations.AddField(
            model_name='fund',
            name='assignment_contract',
            field=models.FileField(blank=True, help_text='Contrato de cesión', null=True, upload_to=apps.utils.models.file_helpers.fund_assignment_contract_path, verbose_name='Contrato de cesión'),
        ),
        migrations.AddField(
            model_name='fund',
            name='operating_contract',
            field=models.FileField(blank=True, help_text='Contrato de operación', null=True, upload_to=apps.utils.models.file_helpers.fund_operating_contract_path, verbose_name='Contrato de operación'),
        ),
        migrations.AddField(
            model_name='fundsemestraldocument',
            name='periodicity',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annually', 'Semestral'), ('annually', 'Anual')], default=1, max_length=20, verbose_name='Periodicidad del documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundsemestraldocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestral_documents', to='fund.typesemestraldocument', verbose_name='Tipo de documento'),
        ),
    ]
