# Generated by Django 5.2.1 on 2026-02-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0020_typesemestraldocument_remove_fund_other_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsemestraldocument',
            name='cycle',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ciclo 1'), (2, 'Ciclo 2'), (3, 'Ciclo 3'), (4, 'Ciclo 4'), (5, 'Ciclo 5'), (6, 'Ciclo 6'), (7, 'Ciclo 7'), (8, 'Ciclo 8'), (9, 'Ciclo 9'), (10, 'Ciclo 10'), (11, 'Ciclo 11'), (12, 'Ciclo 12')], default=1, help_text='Número del ciclo dentro de la periodicidad (Ej: 1-12 para mensual, 1-4 para trimestral, etc.)', verbose_name='Número de ciclo'),
            preserve_default=False,
        ),
    ]
