# Generated by Django 3.2.18 on 2025-05-13 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0020_auto_20250509_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('token_id', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='fund.fund')),
            ],
            options={
                'verbose_name': 'Token de Fondo',
                'verbose_name_plural': 'Tokens de Fondos',
                'ordering': ['-created_at'],
                'unique_together': {('fund', 'token_id')},
            },
        ),
    ]
