# Generated by Django 5.2.1 on 2026-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0021_fundsemestraldocument_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='last_token_seq',
            field=models.PositiveBigIntegerField(blank=True, help_text='Última secuencia numérica utilizada para generar token IDs', null=True, verbose_name='Última secuencia de token'),
        ),
    ]
