# Generated by Django 3.2.18 on 2025-05-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0021_fundtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferreceipt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
