# Generated by Django 5.2.1 on 2026-03-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0022_fund_last_token_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='investmentapplication',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='assistance_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de asistencia'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='authorization_channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Canal de autorización'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='authorization_evidence',
            field=models.TextField(blank=True, help_text='Referencia, ID de llamada, ticket, URL, hash o detalle verificable', null=True, verbose_name='Evidencia de autorización del usuario'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_fund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='data_processing_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento para tratamiento de datos'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='data_processing_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora del consentimiento de datos'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='data_processing_consent_evidence',
            field=models.TextField(blank=True, null=True, verbose_name='Evidencia del consentimiento de datos'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='is_staff_assisted',
            field=models.BooleanField(default=False, verbose_name='¿Creación asistida por staff?'),
        ),
    ]
