# Generated by Django 3.2.18 on 2025-05-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0022_auto_20250521_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferreceipt',
            old_name='transfer_id',
            new_name='transaction_id',
        ),
    ]
