# Generated by Django 3.2.18 on 2025-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0024_auto_20250522_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundtoken',
            name='nickname',
        ),
        migrations.AddField(
            model_name='fund',
            name='nickname_tokens',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
