# Generated by Django 3.2.18 on 2025-05-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0025_auto_20250522_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='number_of_investors',
        ),
    ]
