# Generated by Django 3.2.18 on 2025-05-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0026_remove_fund_number_of_investors'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtoken',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
