# Generated by Django 5.2.1 on 2025-05-28 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0027_fundtoken_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundinvestment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inversión en Fondo', 'verbose_name_plural': 'Inversiones en Fondos'},
        ),
        migrations.AlterUniqueTogether(
            name='fundinvestment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='fund_units_purchased',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Unidades del fondo adquiridas', max_digits=14, verbose_name='Unidades compradas'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='investment_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='status',
            field=models.CharField(choices=[('pending_tokens', 'Pendiente de Tokens'), ('tokens_purchased', 'Tokens Comprados'), ('investment_completed', 'Inversión Completada'), ('investment_cancelled', 'Inversión Cancelada')], default='pending_tokens', max_length=25, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='tokens_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de compra de tokens'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='tokens_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de tokens comprados', verbose_name='Tokens comprados'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='tokens_used_for_investment',
            field=models.PositiveIntegerField(default=0, help_text='Tokens utilizados para esta inversión', verbose_name='Tokens utilizados'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='fund.fund', verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto realmente invertido', max_digits=14, verbose_name='Monto invertido'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_investments', to=settings.AUTH_USER_MODEL, verbose_name='Inversor'),
        ),
        migrations.CreateModel(
            name='FundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Solicitud Pendiente'), ('under_review', 'En Revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=15, verbose_name='Estado')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Monto que el solicitante desea invertir', max_digits=14, verbose_name='Monto solicitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('applicant_notes', models.TextField(blank=True, help_text='Información adicional proporcionada por el solicitante', null=True, verbose_name='Notas del solicitante')),
                ('review_notes', models.TextField(blank=True, help_text='Observaciones del proceso de revisión', null=True, verbose_name='Notas de revisión')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_applications', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fund.fund', verbose_name='Fondo')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Fondo',
                'verbose_name_plural': 'Solicitudes de Fondos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='fund.fundapplication', verbose_name='Solicitud asociada'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['status', 'created_at'], name='fund_fundin_status_bbc629_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['fund', 'investor'], name='fund_fundin_fund_id_e0e51b_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['investor', 'status'], name='fund_fundin_investo_13955f_idx'),
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='joined_at',
        ),
        migrations.AddIndex(
            model_name='fundapplication',
            index=models.Index(fields=['status', 'created_at'], name='fund_fundap_status_143273_idx'),
        ),
        migrations.AddIndex(
            model_name='fundapplication',
            index=models.Index(fields=['fund', 'status'], name='fund_fundap_fund_id_3f10b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundapplication',
            unique_together={('fund', 'applicant')},
        ),
    ]
