# Generated by Django 5.2.1 on 2025-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0028_alter_fundinvestment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinvestment',
            name='fund_units_purchased',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='investment_completion_date',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='tokens_purchase_date',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='tokens_purchased',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='tokens_used_for_investment',
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='status',
            field=models.CharField(choices=[('approved', 'Verificación Aprobada'), ('active', 'Activa'), ('inactive', 'Inactiva'), ('cancelled', 'Cancelada'), ('suspended', 'Suspendida')], default='approved', max_length=25, verbose_name='Estado'),
        ),
    ]
