# Generated by Django 5.2.1 on 2025-06-12 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0029_remove_fundinvestment_fund_units_purchased_and_more'),
        ('trading', '0002_auto_20250410_1158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('MINTED', 'Creación de Token'), ('BURNED', 'Quema de Token'), ('TRANSFER', 'Transferencia de Token'), ('PURCHASE', 'Compra de Token'), ('SOLD', 'Venta de Token'), ('INDEX_TRANSFER', 'Transferencia Index-to-Index')], default='TRANSFER', max_length=20)),
                ('kaleido_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.IntegerField(default=0, help_text='Cantidad de tokens involucrados en la transacción')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('PENDING', 'Pendiente'), ('FAILED', 'Fallida')], default='COMPLETED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='token_transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_transactions', to='fund.fund')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='token_transactions_received', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fund.fundtoken')),
                ('trading_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.transaction')),
            ],
            options={
                'verbose_name': 'Transacción de Token',
                'verbose_name_plural': 'Transacciones de Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
