# Generated by Django 5.2.1 on 2025-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0030_tokentransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtoken',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='reserved_for_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='reserved_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
