# Generated by Django 5.2.1 on 2025-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0031_fundtoken_reservation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='actual_performance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual performance percentage', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='data_processing_policy',
            field=models.FileField(blank=True, help_text='Data processing policy document', null=True, upload_to='funds/policies/'),
        ),
        migrations.AddField(
            model_name='fund',
            name='description_admin',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='description_main_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='expected_profitability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profitability percentage', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='terms_and_conditions',
            field=models.FileField(blank=True, help_text='Terms and conditions document', null=True, upload_to='funds/terms/'),
        ),
    ]
