# Generated by Django 5.2.1 on 2025-08-21 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0032_fund_actual_performance_fund_data_processing_policy_and_more'),
        ('kaleido', '0020_instanceoftokencontract721_promote_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fondo de Inversión', 'verbose_name_plural': 'Fondos de Inversión'},
        ),
        migrations.RenameField(
            model_name='fundtoken',
            old_name='reserved_for_purchase',
            new_name='available_for_trading',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='actual_performance',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='annual_return',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='expected_profitability',
        ),
        migrations.AddField(
            model_name='fund',
            name='accountability',
            field=models.FileField(blank=True, help_text='Documento de rendición de cuentas', null=True, upload_to='funds/accountability/', verbose_name='Rendición de cuentas'),
        ),
        migrations.AddField(
            model_name='fund',
            name='current_annual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendimiento anualizado porcentual', max_digits=6, null=True, verbose_name='Rendimiento anual actual (%)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='current_return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de rendimiento actual', max_digits=6, null=True, verbose_name='Tasa de retorno actual (%)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='expected_return',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de rentabilidad esperada', max_digits=6, null=True, verbose_name='Retorno esperado (%)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='image_admin',
            field=models.ImageField(blank=True, null=True, upload_to='funds/images/', verbose_name='Imagen administrativa'),
        ),
        migrations.AddField(
            model_name='fund',
            name='operator_report',
            field=models.FileField(blank=True, help_text='Reporte del operador', null=True, upload_to='funds/reports/', verbose_name='Reporte del operador'),
        ),
        migrations.AddField(
            model_name='fund',
            name='performance_payment_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semi_annually', 'Semestral'), ('annually', 'Anual')], max_length=20, null=True, verbose_name='Frecuencia de pago de rendimientos'),
        ),
        migrations.AddField(
            model_name='fund',
            name='suggested_trend',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiempo sugerido para mantener la inversión en años', null=True, verbose_name='Tendencia sugerida (años)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='tax_certificate',
            field=models.FileField(blank=True, help_text='Documento de certificado tributario', null=True, upload_to='funds/tax_certificates/', verbose_name='Certificado tributario'),
        ),
        migrations.AddField(
            model_name='fund',
            name='tir',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa Interna de Retorno porcentual', max_digits=6, null=True, verbose_name='TIR (%)'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='accepts_risk_disclosure',
            field=models.BooleanField(default=False, verbose_name='Acepta declaración de riesgos'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='accepts_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Acepta términos y condiciones'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='application_version',
            field=models.CharField(blank=True, help_text='Versión del formulario usado', max_length=20, null=True, verbose_name='Versión de la aplicación'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='authorizes_background_check',
            field=models.BooleanField(default=False, verbose_name='Autoriza verificación de antecedentes'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='confirms_information_accuracy',
            field=models.BooleanField(default=False, verbose_name='Confirma veracidad de la información'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('professional', 'Profesional')], max_length=20, null=True, verbose_name='Experiencia en inversión'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='investment_objective',
            field=models.CharField(blank=True, choices=[('capital_growth', 'Crecimiento de Capital'), ('income_generation', 'Generación de Ingresos'), ('capital_preservation', 'Preservación de Capital'), ('retirement', 'Jubilación'), ('education', 'Educación'), ('other', 'Otro')], max_length=30, null=True, verbose_name='Objetivo de inversión'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP de solicitud'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='is_politically_exposed',
            field=models.BooleanField(default=False, help_text='PEP - Persona Expuesta Políticamente', verbose_name='¿Es persona políticamente expuesta?'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='maximum_acceptable_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio máximo que está dispuesto a pagar por unidad', max_digits=10, null=True, verbose_name='Precio máximo aceptable por unidad'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='planned_investment_horizon',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiempo que planea mantener la inversión', null=True, verbose_name='Horizonte de inversión planeado (años)'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia Bancaria'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta Débito'), ('check', 'Cheque'), ('crypto', 'Criptomonedas'), ('other', 'Otro')], max_length=30, null=True, verbose_name='Método de pago preferido'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'Sitio Web'), ('social_media', 'Redes Sociales'), ('referral', 'Referido'), ('advisor', 'Asesor Financiero'), ('advertisement', 'Publicidad'), ('event', 'Evento'), ('other', 'Otro')], max_length=30, null=True, verbose_name='¿Cómo se enteró del fondo?'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='requested_units',
            field=models.PositiveIntegerField(blank=True, help_text='Número específico de unidades que desea adquirir', null=True, verbose_name='Unidades solicitadas'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=15, null=True, verbose_name='Tolerancia al riesgo'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='source_of_funds',
            field=models.CharField(blank=True, choices=[('salary', 'Salario'), ('business_income', 'Ingresos de Negocio'), ('investments', 'Inversiones'), ('inheritance', 'Herencia'), ('loan', 'Préstamo'), ('savings', 'Ahorros'), ('other', 'Otro')], max_length=30, null=True, verbose_name='Fuente de los fondos'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Cualquier instrucción o requerimiento especial', null=True, verbose_name='Instrucciones especiales'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent del navegador'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='accepts_risk_disclosure',
            field=models.BooleanField(default=False, help_text='Confirmación específica de riesgos para esta inversión', verbose_name='Acepta declaración de riesgos de la inversión'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='accepts_terms_and_conditions',
            field=models.BooleanField(default=False, help_text='Confirmación específica para esta inversión', verbose_name='Acepta términos y condiciones de la inversión'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intereses devengados pero no pagados', max_digits=14, verbose_name='Intereses acumulados'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list, help_text='Log de cambios importantes en la inversión', verbose_name='Historial de cambios'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='auto_reinvest_dividends',
            field=models.BooleanField(default=True, help_text='Si los dividendos se reinvierten automáticamente', verbose_name='Reinversión automática de dividendos'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Para pagos de dividendos y redenciones', max_length=50, null=True, verbose_name='Número de cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del banco'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de enrutamiento bancario'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_investments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='current_unit_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio actual de mercado por unidad', max_digits=10, null=True, verbose_name='Valor actual por unidad'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='dividend_payment_preference',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('reinvest', 'Reinversión'), ('mixed', 'Mixto')], default='reinvest', max_length=20, verbose_name='Preferencia de pago de dividendos'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='investment_agreement',
            field=models.FileField(blank=True, null=True, upload_to='investments/agreements/', verbose_name='Contrato de inversión firmado'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='investment_notes',
            field=models.TextField(blank=True, help_text='Observaciones específicas de esta inversión', null=True, verbose_name='Notas de la inversión'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='investment_start_date',
            field=models.DateField(blank=True, help_text='Fecha cuando la inversión se activa oficialmente', null=True, verbose_name='Fecha de inicio de inversión'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='last_dividend_date',
            field=models.DateField(blank=True, help_text='Última vez que recibió dividendos', null=True, verbose_name='Última fecha de dividendo'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_investments', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='last_valuation_date',
            field=models.DateTimeField(blank=True, help_text='Última vez que se calculó el valor de la inversión', null=True, verbose_name='Última fecha de valoración'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='management_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de comisiones de administración pagadas', max_digits=14, verbose_name='Comisiones de administración pagadas'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='maturity_date',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del período de permanencia', null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago confirmado'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia Bancaria'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta Débito'), ('check', 'Cheque'), ('wire_transfer', 'Transferencia Internacional'), ('crypto', 'Criptomonedas'), ('ach', 'ACH'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=30, null=True, verbose_name='Método de pago utilizado'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='investments/receipts/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Número de transacción, cheque, etc.', max_length=100, null=True, verbose_name='Referencia de pago'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=15, verbose_name='Estado del pago'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='pending_dividends',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dividendos declarados pero no pagados', max_digits=14, verbose_name='Dividendos pendientes'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='performance_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de comisiones por desempeño pagadas', max_digits=14, verbose_name='Comisiones de performance pagadas'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='purchase_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio al cual compró las unidades', max_digits=10, null=True, verbose_name='Precio de compra por unidad'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='realized_capital_gains',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ganancias por ventas parciales ya realizadas', max_digits=14, verbose_name='Ganancias de capital realizadas'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de suspensión'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='tax_documents',
            field=models.FileField(blank=True, null=True, upload_to='investments/tax/', verbose_name='Documentos fiscales'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='tax_withholding_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de impuestos retenidos automáticamente', max_digits=5, verbose_name='Porcentaje de retención fiscal (%)'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='total_dividends_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total de dividendos recibidos históricamente', max_digits=14, verbose_name='Total dividendos recibidos'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='units_owned',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Número de unidades del fondo que posee', max_digits=12, verbose_name='Unidades poseídas'),
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='unrealized_capital_gains',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ganancias en papel basadas en precio actual', max_digits=14, verbose_name='Ganancias de capital no realizadas'),
        ),
        migrations.AddField(
            model_name='fundtoken',
            name='fund_investment',
            field=models.ForeignKey(blank=True, help_text='Inversión específica a la que pertenece este token', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='fund.fundinvestment', verbose_name='Inversión asociada'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de tokens del fondo', verbose_name='Cantidad de tokens'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount_units',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de unidades del fondo', verbose_name='Cantidad de unidades'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='asset_composition',
            field=models.JSONField(blank=True, help_text='Distribución porcentual por tipo de activo', null=True, verbose_name='Composición de activos'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='data_processing_policy',
            field=models.FileField(blank=True, help_text='Documento de política de tratamiento de datos', null=True, upload_to='funds/policies/', verbose_name='Política de tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description_admin',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción administrativa'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description_main_manager',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del gerente principal'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='dividend_distribution',
            field=models.CharField(blank=True, choices=[('automatic_reinvestment', 'Reinversión Automática'), ('periodic_distribution', 'Distribución Periódica'), ('mixed', 'Mixto')], max_length=25, null=True, verbose_name='Distribución de dividendos'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='early_withdrawal_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de penalización por retiro anticipado', max_digits=5, null=True, verbose_name='Penalización retiro anticipado (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('real_estate', 'Fondo Inmobiliario'), ('securities', 'Fondo de Valores'), ('private_equity', 'Capital Privado'), ('pension', 'Pensión Voluntaria'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Tipo de fondo'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='hd_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaleido.wallet', verbose_name='Wallet HD'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='funds/images/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='initial_unit_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor inicial por unidad'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='investment_horizon',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiempo recomendado en años', null=True, verbose_name='Horizonte de inversión (años)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='main_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerente principal'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='management_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compañía administradora'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión de administración', max_digits=5, null=True, verbose_name='Comisión de administración (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='minimum_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Inversión mínima'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del fondo'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='nickname_tokens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de los tokens'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='operations_closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre de operaciones'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='operations_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de operaciones'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='permanence_period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiempo mínimo en días', null=True, verbose_name='Período de permanencia (días)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por unidad actual'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='risk_profile',
            field=models.CharField(blank=True, choices=[('conservative', 'Conservador'), ('moderate', 'Moderado'), ('aggressive', 'Agresivo')], max_length=15, null=True, verbose_name='Perfil de riesgo'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='risk_rating',
            field=models.CharField(blank=True, help_text='Ej.: AAA, AA+, BBB, etc.', max_length=10, null=True, verbose_name='Calificación de riesgo'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave secreta'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='success_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión por desempeño', max_digits=5, null=True, verbose_name='Comisión de éxito (%)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='superintendency_registry',
            field=models.CharField(blank=True, help_text='Número de registro en Superintendencia Financiera', max_length=50, null=True, verbose_name='Registro superintendencia'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Número de identificación tributaria', max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='terms_and_conditions',
            field=models.FileField(blank=True, help_text='Documento de términos y condiciones', null=True, upload_to='funds/terms/', verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='token_contract_721',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kaleido.instanceoftokencontract721', verbose_name='Contrato de Token 721'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Activos totales'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='trading_hours',
            field=models.CharField(blank=True, help_text='Ej.: 8:00 a.m. - 1:00 p.m.', max_length=100, null=True, verbose_name='Horario de operaciones'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto realmente invertido confirmado', max_digits=14, verbose_name='Monto invertido'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pago Pendiente'), ('payment_verified', 'Pago Verificado'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('mature', 'Vencida'), ('partial_redemption', 'Redención Parcial'), ('full_redemption', 'Redención Total'), ('cancelled', 'Cancelada')], default='pending_payment', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='fundinvestment',
            unique_together={('fund', 'investor', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['status', 'fund_type'], name='fund_fund_status_6b73c2_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['created_at'], name='fund_fund_created_ad2458_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['name'], name='fund_fund_name_3bd753_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['investment_start_date'], name='fund_fundin_investm_b0bbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['maturity_date'], name='fund_fundin_maturit_7ff88c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvestment',
            index=models.Index(fields=['payment_status'], name='fund_fundin_payment_760a8d_idx'),
        ),
    ]
