# Generated by Django 5.2.1 on 2025-08-28 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0033_alter_fund_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='accountability',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='operator_report',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='tax_certificate',
        ),
        migrations.AddField(
            model_name='fund',
            name='evolution_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Evolución del fondo'),
        ),
        migrations.CreateModel(
            name='FundSemestralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('accountability', 'Rendición de cuentas'), ('tax_certificate', 'Certificado tributario'), ('operator_report', 'Reporte del operador')], max_length=50, verbose_name='Tipo de documento')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año del documento')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], verbose_name='Semestre del documento')),
                ('document', models.FileField(upload_to='funds/semestral_documents/', verbose_name='Documento semestral')),
                ('title', models.CharField(max_length=255, verbose_name='Título del documento')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del documento')),
                ('period_start_date', models.DateField(verbose_name='Fecha de inicio del período')),
                ('period_end_date', models.DateField(verbose_name='Fecha de fin del período')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestral_documents', to='fund.fund', verbose_name='Fondo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento Semestral',
                'verbose_name_plural': 'Documentos Semestrales',
                'ordering': ['-uploaded_date'],
                'indexes': [models.Index(fields=['fund', 'uploaded_date'], name='fund_fundse_fund_id_e2b2bd_idx')],
            },
        ),
    ]
