# Generated by Django 5.2.1 on 2025-09-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0033_alter_fund_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('expired', 'Expirado'), ('revoked', 'Revocado'), ('pre_approved', 'Pre-aprobado'), ('pre_approved_with_changes', 'Pre-aprobado con cambios'), ('awaiting_contract_signature', 'En espera de firma de contrato'), ('contract_signed', 'Contrato firmado')], default='pre_approved', max_length=40, verbose_name='Estado de la aprobación')),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto aprobado')),
                ('approved_units', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades aprobadas')),
                ('unit_price_at_approval', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por unidad al momento de la aprobación')),
                ('terms_and_conditions_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión de términos y condiciones')),
                ('risk_disclosure_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión de declaración de riesgos')),
                ('initial_terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de términos iniciales')),
                ('initial_terms_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión de términos iniciales aceptados')),
                ('pre_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pre-aprobación')),
                ('terms_modified', models.BooleanField(default=False, verbose_name='Términos fueron modificados durante revisión')),
                ('changes_summary', models.TextField(blank=True, help_text='Descripción de los cambios entre lo solicitado y lo aprobado', null=True, verbose_name='Resumen de cambios realizados')),
                ('final_contract_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación del contrato final')),
                ('final_contract_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío del contrato final al usuario')),
                ('final_contract_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma del contrato final')),
                ('contract_signature_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite para firmar el contrato')),
                ('contract_document_id', models.CharField(blank=True, help_text='Referencia al documento en el sistema de gestión documental', max_length=100, null=True, verbose_name='ID del documento de contrato')),
                ('digital_signature_id', models.CharField(blank=True, help_text='Referencia de la firma digital en el sistema', max_length=100, null=True, verbose_name='ID de la firma digital')),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aprobación de Fondo',
            },
        ),
        migrations.CreateModel(
            name='FundSemestralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('accountability', 'Rendición de cuentas'), ('tax_certificate', 'Certificado tributario'), ('operator_report', 'Reporte del operador')], max_length=50, verbose_name='Tipo de documento')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año del documento')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], verbose_name='Semestre del documento')),
                ('document', models.FileField(upload_to='funds/semestral_documents/', verbose_name='Documento semestral')),
                ('title', models.CharField(max_length=255, verbose_name='Título del documento')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del documento')),
                ('period_start_date', models.DateField(verbose_name='Fecha de inicio del período')),
                ('period_end_date', models.DateField(verbose_name='Fecha de fin del período')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Documento Semestral',
                'verbose_name_plural': 'Documentos Semestrales',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='fundapplication',
            name='fund_fundap_fund_id_3f10b2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='fundapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fund',
            name='accountability',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='operator_report',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='tax_certificate',
        ),
        migrations.RemoveField(
            model_name='fundinvestment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='fundpricehistory',
            name='status',
        ),
        migrations.AddField(
            model_name='fund',
            name='evolution_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Evolución del fondo'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='can_reapply_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('insufficient_funds', 'Fondos Insuficientes'), ('failed_kyc', 'Fallo en KYC'), ('failed_background_check', 'Fallo en Verificación de Antecedentes'), ('high_risk_profile', 'Perfil de Alto Riesgo'), ('incomplete_application', 'Aplicación Incompleta')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='applicant_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('professional', 'Profesional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='investment_objective',
            field=models.CharField(blank=True, choices=[('capital_growth', 'Crecimiento de Capital'), ('income_generation', 'Generación de Ingresos'), ('capital_preservation', 'Preservación de Capital'), ('retirement', 'Jubilación'), ('education', 'Educación'), ('other', 'Otro')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='ip_address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='is_politically_exposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='maximum_acceptable_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio máximo aceptable por unidad'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia Bancaria'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta Débito'), ('check', 'Cheque'), ('crypto', 'Criptomonedas'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'Sitio Web'), ('social_media', 'Redes Sociales'), ('referral', 'Referido'), ('advisor', 'Asesor Financiero'), ('advertisement', 'Publicidad'), ('event', 'Evento'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto solicitado'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='requested_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades solicitadas'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='source_of_funds',
            field=models.CharField(blank=True, choices=[('salary', 'Salario'), ('business_income', 'Ingresos de Negocio'), ('investments', 'Inversiones'), ('inheritance', 'Herencia'), ('loan', 'Préstamo'), ('savings', 'Ahorros'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Solicitud Pendiente'), ('under_review', 'En Revisión'), ('additional_info_required', 'Información Adicional Requerida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada'), ('expired', 'Expirada')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundtoken',
            name='fund_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='fund.fundinvestment', verbose_name='Inversión asociada'),
        ),
        migrations.AddIndex(
            model_name='fundapplication',
            index=models.Index(fields=['fund', 'applicant'], name='fund_fundap_fund_id_920885_idx'),
        ),
        migrations.AddField(
            model_name='fundapproval',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='fund.fundapplication', verbose_name='Solicitud Asociada'),
        ),
        migrations.AddField(
            model_name='fundapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='fundsemestraldocument',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestral_documents', to='fund.fund', verbose_name='Fondo'),
        ),
        migrations.AddField(
            model_name='fundsemestraldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.RemoveField(
            model_name='fundapplication',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='fundsemestraldocument',
            index=models.Index(fields=['fund', 'uploaded_date'], name='fund_fundse_fund_id_e2b2bd_idx'),
        ),
    ]
