# Generated by Django 5.2.1 on 2025-09-02 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0034_remove_fund_accountability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fundapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fundpricehistory',
            name='status',
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='can_reapply_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('insufficient_funds', 'Fondos Insuficientes'), ('failed_kyc', 'Fallo en KYC'), ('failed_background_check', 'Fallo en Verificación de Antecedentes'), ('high_risk_profile', 'Perfil de Alto Riesgo'), ('incomplete_application', 'Aplicación Incompleta')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='applicant_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('professional', 'Profesional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='investment_objective',
            field=models.CharField(blank=True, choices=[('capital_growth', 'Crecimiento de Capital'), ('income_generation', 'Generación de Ingresos'), ('capital_preservation', 'Preservación de Capital'), ('retirement', 'Jubilación'), ('education', 'Educación'), ('other', 'Otro')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='is_politically_exposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Transferencia Bancaria'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta Débito'), ('check', 'Cheque'), ('crypto', 'Criptomonedas'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'Sitio Web'), ('social_media', 'Redes Sociales'), ('referral', 'Referido'), ('advisor', 'Asesor Financiero'), ('advertisement', 'Publicidad'), ('event', 'Evento'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='source_of_funds',
            field=models.CharField(blank=True, choices=[('salary', 'Salario'), ('business_income', 'Ingresos de Negocio'), ('investments', 'Inversiones'), ('inheritance', 'Herencia'), ('loan', 'Préstamo'), ('savings', 'Ahorros'), ('other', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Solicitud Pendiente'), ('under_review', 'En Revisión'), ('additional_info_required', 'Información Adicional Requerida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada'), ('expired', 'Expirada')], default='pending', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundtoken',
            name='fund_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='fund.fundinvestment', verbose_name='Inversión asociada'),
        ),
        migrations.CreateModel(
            name='FundApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('expired', 'Expirado'), ('revoked', 'Revocado'), ('pre_approved', 'Pre-aprobado'), ('pre_approved_with_changes', 'Pre-aprobado con cambios'), ('awaiting_contract_signature', 'En espera de firma de contrato'), ('contract_signed', 'Contrato firmado')], default='pre_approved', max_length=40, verbose_name='Estado de la aprobación')),
                ('approved_amount', models.DecimalField(decimal_places=2, help_text='Monto que ha sido aprobado para inversión', max_digits=14, verbose_name='Monto aprobado')),
                ('approved_units', models.PositiveIntegerField(blank=True, help_text='Número de unidades aprobadas para adquisición', null=True, verbose_name='Unidades aprobadas')),
                ('unit_price_at_approval', models.DecimalField(decimal_places=2, help_text='Precio unitario vigente al momento de la aprobación', max_digits=10, verbose_name='Precio por unidad al momento de la aprobación')),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('terms_and_conditions_version', models.CharField(blank=True, help_text='Versión de los términos aceptados', max_length=20, null=True, verbose_name='Versión de términos y condiciones')),
                ('risk_disclosure_version', models.CharField(blank=True, help_text='Versión de la declaración de riesgos aceptada', max_length=20, null=True, verbose_name='Versión de declaración de riesgos')),
                ('initial_terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de términos iniciales')),
                ('initial_terms_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versión de términos iniciales aceptados')),
                ('pre_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pre-aprobación')),
                ('terms_modified', models.BooleanField(default=False, verbose_name='Términos fueron modificados durante revisión')),
                ('changes_summary', models.TextField(blank=True, help_text='Descripción de los cambios entre lo solicitado y lo aprobado', null=True, verbose_name='Resumen de cambios realizados')),
                ('final_contract_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación del contrato final')),
                ('final_contract_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío del contrato final al usuario')),
                ('final_contract_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma del contrato final')),
                ('contract_signature_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite para firmar el contrato')),
                ('contract_document_id', models.CharField(blank=True, help_text='Referencia al documento en el sistema de gestión documental', max_length=100, null=True, verbose_name='ID del documento de contrato')),
                ('digital_signature_id', models.CharField(blank=True, help_text='Referencia de la firma digital en el sistema', max_length=100, null=True, verbose_name='ID de la firma digital')),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='fund.fundapplication', verbose_name='Solicitud Asociada')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
            ],
            options={
                'verbose_name': 'Aprobación de Fondo',
                'ordering': ['-approval_date'],
            },
        ),
        migrations.RemoveField(
            model_name='fundapplication',
            name='updated_at',
        ),
    ]
