# Generated by Django 5.2.1 on 2025-09-11 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0034_fundapproval_fundsemestraldocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundapproval',
            name='application',
        ),
        migrations.RemoveField(
            model_name='fundapproval',
            name='approved_by',
        ),
        migrations.CreateModel(
            name='InvestorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_signature', 'Pendiente de Firma'), ('contract_signed', 'Contrato Firmado'), ('suspended', 'Suspendido')], default='pending_signature', max_length=20, verbose_name='Estado de aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('contract_url', models.URLField(blank=True, null=True, verbose_name='URL del contrato a firmar')),
                ('contract_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma del contrato')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración para firma')),
                ('suspension_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de suspensión')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de suspensión')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contracts', to='fund.fund', verbose_name='Fondo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contrato de Inversor',
                'verbose_name_plural': 'Contratos de Inversores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FundApplication',
        ),
        migrations.DeleteModel(
            name='FundApproval',
        ),
    ]
