# Generated by Django 3.2.18 on 2025-02-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0010_instanceoftokencontract721'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceoftokencontract721',
            name='instance_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
