# Generated by Django 3.2.18 on 2025-02-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0012_alter_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceoftokencontract721',
            name='instance_id',
        ),
    ]
