# Generated by Django 3.2.18 on 2025-02-24 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kaleido', '0013_remove_instanceoftokencontract721_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceoftokencontract721',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
