# Generated by Django 3.2.18 on 2025-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0014_alter_instanceoftokencontract721_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceoftokencontract721',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
