# Generated by Django 3.2.18 on 2025-02-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0017_compilecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilecontract',
            name='app_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='kaleido.appcontract'),
        ),
        migrations.AddField(
            model_name='compilecontract',
            name='compiled_contract_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
