# Generated by Django 3.2.18 on 2025-02-26 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kaleido', '0018_auto_20250226_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoteContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('app_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='kaleido.appcontract')),
                ('compiled_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='kaleido.compilecontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
