# Generated by Django 3.2.18 on 2025-02-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0019_promotecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceoftokencontract721',
            name='promote_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_instances', to='kaleido.promotecontract'),
        ),
    ]
