# Generated by Django 3.2.18 on 2025-05-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='blockchain_tx_hash',
        ),
    ]
