# Generated by Django 5.2.1 on 2025-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditlog_blockchain_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Éxito'), ('ERROR', 'Error'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20),
        ),
    ]
