# Generated by Django 5.2.1 on 2025-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
